In [1]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.50)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 8.2 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.9.0

In [2]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [9]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-06-30 13:24:32,404] A new study created in memory with name: no-name-c28d0e61-ea34-450b-b9a0-35d34c8b3dd8
[I 2026-06-30 13:24:33,051] Trial 0 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 68, 'max_depth': 5}. Best is trial 0 with value: 0.7746741154562384.
[I 2026-06-30 13:24:33,726] Trial 1 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 74, 'max_depth': 19}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:35,544] Trial 2 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 199, 'max_depth': 11}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:36,149] Trial 3 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 114, 'max_depth': 12}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:36,870] Trial 4 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 142, 'max_depth': 14}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:37,639] Trial 5 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 150, 'max_depth': 18}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:38,499] Trial 6 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 158, 'max_depth': 14}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:39,453] Trial 7 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 191, 'max_depth': 6}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:40,043] Trial 8 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 74, 'max_depth': 12}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:40,501] Trial 9 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 56, 'max_depth': 13}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:41,312] Trial 10 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 101, 'max_depth': 20}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:41,917] Trial 11 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 80, 'max_depth': 4}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:42,199] Trial 12 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 51, 'max_depth': 7}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:42,481] Trial 13 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 52, 'max_depth': 9}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:42,983] Trial 14 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 96, 'max_depth': 17}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:43,426] Trial 15 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 87, 'max_depth': 8}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:43,970] Trial 16 finished with value: 0.756052141527002 and parameters: {'n_estimators': 120, 'max_depth': 3}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:44,242] Trial 17 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 51, 'max_depth': 17}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:44,599] Trial 18 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 68, 'max_depth': 7}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:45,176] Trial 19 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 112, 'max_depth': 20}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:45,653] Trial 20 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 90, 'max_depth': 9}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-06-30 13:24:45,968] Trial 21 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 66, 'max_depth': 5}. Best is trial 21 with value: 0.7783985102420856.
[I 2026-06-30 13:24:46,281] Trial 22 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 64, 'max_depth': 5}. Best is trial 21 with value: 0.7783985102420856.
[I 2026-06-30 13:24:46,690] Trial 23 finished with value: 0.7597765363128492 and parameters: {'n_estimators': 76, 'max_depth': 10}. Best is trial 21 with value: 0.7783985102420856.
[I 2026-06-30 13:24:46,968] Trial 24 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 61, 'max_depth': 3}. Best is trial 21 with value: 0.7783985102420856.
[I 2026-06-30 13:24:47,369] Trial 25 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 82, 'max_depth': 7}. Best is trial 21 with value: 0.7783985102420856.
[I 2026-06-30 13:24:47,898] Trial 26 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 101, 'max_depth': 15}. Best is trial 21 with value: 0.7783985102420856.
[I 2026-06-30 13:24:48,159] Trial 27 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 50, 'max_depth': 6}. Best is trial 21 with value: 0.7783985102420856.
[I 2026-06-30 13:24:48,529] Trial 28 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 69, 'max_depth': 16}. Best is trial 21 with value: 0.7783985102420856.
[I 2026-06-30 13:24:48,848] Trial 29 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 62, 'max_depth': 5}. Best is trial 21 with value: 0.7783985102420856.
[I 2026-06-30 13:24:49,477] Trial 30 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 125, 'max_depth': 19}. Best is trial 30 with value: 0.7802607076350093.
[I 2026-06-30 13:24:50,166] Trial 31 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 131, 'max_depth': 19}. Best is trial 30 with value: 0.7802607076350093.
[I 2026-06-30 13:24:51,213] Trial 32 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 131, 'max_depth': 19}. Best is trial 30 with value: 0.7802607076350093.
[I 2026-06-30 13:24:52,610] Trial 33 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 134, 'max_depth': 19}. Best is trial 30 with value: 0.7802607076350093.
[I 2026-06-30 13:24:55,051] Trial 34 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 164, 'max_depth': 18}. Best is trial 30 with value: 0.7802607076350093.
[I 2026-06-30 13:24:56,920] Trial 35 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 128, 'max_depth': 19}. Best is trial 30 with value: 0.7802607076350093.
[I 2026-06-30 13:24:59,877] Trial 36 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 173, 'max_depth': 16}. Best is trial 30 with value: 0.7802607076350093.
[I 2026-06-30 13:25:01,639] Trial 37 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 143, 'max_depth': 18}. Best is trial 30 with value: 0.7802607076350093.
[I 2026-06-30 13:25:03,446] Trial 38 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 123, 'max_depth': 20}. Best is trial 30 with value: 0.7802607076350093.
[I 2026-06-30 13:25:04,958] Trial 39 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 112, 'max_depth': 17}. Best is trial 30 with value: 0.7802607076350093.
[I 2026-06-30 13:25:07,790] Trial 40 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 137, 'max_depth': 14}. Best is trial 30 with value: 0.7802607076350093.
[I 2026-06-30 13:25:09,320] Trial 41 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 122, 'max_depth': 20}. Best is trial 30 with value: 0.7802607076350093.
[I 2026-06-30 13:25:10,677] Trial 42 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 146, 'max_depth': 19}. Best is trial 30 with value: 0.7802607076350093.
[I 2026-06-30 13:25:12,021] Trial 43 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 154, 'max_depth': 20}. Best is trial 30 with value: 0.7802607076350093.
[I 2026-06-30 13:25:13,205] Trial 44 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 129, 'max_depth': 18}. Best is trial 30 with value: 0.7802607076350093.
[I 2026-06-30 13:25:14,551] Trial 45 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 166, 'max_depth': 12}. Best is trial 30 with value: 0.7802607076350093.
[I 2026-06-30 13:25:16,193] Trial 46 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 185, 'max_depth': 16}. Best is trial 30 with value: 0.7802607076350093.
[I 2026-06-30 13:25:17,314] Trial 47 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 124, 'max_depth': 19}. Best is trial 30 with value: 0.7802607076350093.
[I 2026-06-30 13:25:18,351] Trial 48 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 106, 'max_depth': 19}. Best is trial 30 with value: 0.7802607076350093.
[I 2026-06-30 13:25:19,428] Trial 49 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 135, 'max_depth': 15}. Best is trial 30 with value: 0.7802607076350093.

In [10]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 125, 'max_depth': 19}

In [11]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

Random search Sampler

In [12]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-06-30 13:26:08,977] A new study created in memory with name: no-name-26c7bc8c-fc7a-486e-99ec-2244bd5a9c67
[I 2026-06-30 13:26:10,593] Trial 0 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 173, 'max_depth': 8}. Best is trial 0 with value: 0.7635009310986964.
[I 2026-06-30 13:26:11,461] Trial 1 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 90, 'max_depth': 16}. Best is trial 1 with value: 0.7653631284916201.
[I 2026-06-30 13:26:12,829] Trial 2 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 133, 'max_depth': 15}. Best is trial 2 with value: 0.7746741154562383.
[I 2026-06-30 13:26:13,439] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 129, 'max_depth': 6}. Best is trial 2 with value: 0.7746741154562383.
[I 2026-06-30 13:26:13,807] Trial 4 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 69, 'max_depth': 16}. Best is trial 2 with value: 0.7746741154562383.
[I 2026-06-30 13:26:14,637] Trial 5 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 162, 'max_depth': 15}. Best is trial 2 with value: 0.7746741154562383.
[I 2026-06-30 13:26:15,069] Trial 6 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 81, 'max_depth': 15}. Best is trial 2 with value: 0.7746741154562383.
[I 2026-06-30 13:26:15,727] Trial 7 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 137, 'max_depth': 4}. Best is trial 2 with value: 0.7746741154562383.
[I 2026-06-30 13:26:16,732] Trial 8 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 199, 'max_depth': 17}. Best is trial 8 with value: 0.7765363128491619.
[I 2026-06-30 13:26:17,636] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 182, 'max_depth': 10}. Best is trial 8 with value: 0.7765363128491619.
[I 2026-06-30 13:26:19,954] Trial 10 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 187, 'max_depth': 12}. Best is trial 8 with value: 0.7765363128491619.
[I 2026-06-30 13:26:21,255] Trial 11 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 140, 'max_depth': 13}. Best is trial 8 with value: 0.7765363128491619.
[I 2026-06-30 13:26:23,021] Trial 12 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 191, 'max_depth': 20}. Best is trial 8 with value: 0.7765363128491619.
[I 2026-06-30 13:26:23,876] Trial 13 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 102, 'max_depth': 6}. Best is trial 8 with value: 0.7765363128491619.
[I 2026-06-30 13:26:24,472] Trial 14 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 63, 'max_depth': 13}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:25,505] Trial 15 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 125, 'max_depth': 3}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:26,594] Trial 16 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 173, 'max_depth': 10}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:26,910] Trial 17 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 66, 'max_depth': 6}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:28,783] Trial 18 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 188, 'max_depth': 12}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:30,724] Trial 19 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 151, 'max_depth': 9}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:33,858] Trial 20 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 177, 'max_depth': 12}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:35,754] Trial 21 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 185, 'max_depth': 14}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:37,217] Trial 22 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 163, 'max_depth': 20}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:38,208] Trial 23 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 114, 'max_depth': 5}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:39,429] Trial 24 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 143, 'max_depth': 7}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:39,876] Trial 25 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:41,105] Trial 26 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 161, 'max_depth': 6}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:41,504] Trial 27 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 70, 'max_depth': 12}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:41,983] Trial 28 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 91, 'max_depth': 12}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:42,344] Trial 29 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 68, 'max_depth': 9}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:42,726] Trial 30 finished with value: 0.750465549348231 and parameters: {'n_estimators': 85, 'max_depth': 3}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:43,177] Trial 31 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 87, 'max_depth': 13}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:43,904] Trial 32 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 91, 'max_depth': 10}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:45,840] Trial 33 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 187, 'max_depth': 16}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:47,996] Trial 34 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 197, 'max_depth': 14}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:49,157] Trial 35 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 170, 'max_depth': 4}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:50,437] Trial 36 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 151, 'max_depth': 13}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:51,445] Trial 37 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 119, 'max_depth': 17}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:52,860] Trial 38 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 167, 'max_depth': 18}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:53,379] Trial 39 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 77, 'max_depth': 17}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:53,877] Trial 40 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 91, 'max_depth': 11}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:54,491] Trial 41 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 74, 'max_depth': 13}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:55,523] Trial 42 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 123, 'max_depth': 11}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:56,764] Trial 43 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 147, 'max_depth': 11}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:59,154] Trial 44 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 156, 'max_depth': 16}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:26:59,832] Trial 45 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 105, 'max_depth': 3}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:27:00,213] Trial 46 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 83, 'max_depth': 3}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:27:01,191] Trial 47 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 195, 'max_depth': 10}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:27:02,071] Trial 48 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 185, 'max_depth': 6}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-06-30 13:27:02,515] Trial 49 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 88, 'max_depth': 15}. Best is trial 14 with value: 0.7783985102420857.

In [13]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7783985102420857
Best hyperparameters: {'n_estimators': 63, 'max_depth': 13}

In [14]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

Grid search sampler

In [15]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [16]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-06-30 13:27:20,966] A new study created in memory with name: no-name-7ca8b619-493f-4dca-b87d-a4438ace2ca1
[I 2026-06-30 13:27:21,575] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-06-30 13:27:22,735] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-06-30 13:27:23,146] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-30 13:27:23,914] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-30 13:27:24,414] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-30 13:27:24,881] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-30 13:27:26,410] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-30 13:27:28,061] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-30 13:27:29,661] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-30 13:27:31,168] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-30 13:27:32,169] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-30 13:27:33,185] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-30 13:27:34,603] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-30 13:27:35,396] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-06-30 13:27:36,740] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-06-30 13:27:37,327] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [17]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [18]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

Optuna visualization

In [19]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [20]:
# 1. Optimization History
plot_optimization_history(study).show()

In [21]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [22]:
# 3. Slice Plot
plot_slice(study).show()

In [23]:
# 4. Contour Plot
plot_contour(study).show()

In [24]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

## Optimizing Multiple ML Models

In [25]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [26]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [27]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-06-30 13:30:59,487] A new study created in memory with name: no-name-3de454de-50bb-4756-9818-7a9a09af528f
[I 2026-06-30 13:31:00,609] Trial 0 finished with value: 0.761638733705773 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 114, 'learning_rate': 0.15527926535347586, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.761638733705773.
[I 2026-06-30 13:31:03,780] Trial 1 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 162, 'learning_rate': 0.07719376998640369, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 7}. Best is trial 0 with value: 0.761638733705773.
[I 2026-06-30 13:31:08,026] Trial 2 finished with value: 0.7355679702048418 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 208, 'learning_rate': 0.09992291824384114, 'max_depth': 16, 'min_samples_split': 4, 'min_samples_leaf': 7}. Best is trial 0 with value: 0.761638733705773.
[I 2026-06-30 13:31:09,897] Trial 3 finished with value: 0.7448789571694601 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 110, 'learning_rate': 0.026920708743346903, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.761638733705773.
[I 2026-06-30 13:31:10,001] Trial 4 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 12.969653394005043, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-06-30 13:31:11,502] Trial 5 finished with value: 0.74487895716946 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 95, 'learning_rate': 0.06611771921304982, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 7}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-06-30 13:31:11,544] Trial 6 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 67.52933862886091, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-06-30 13:31:14,350] Trial 7 finished with value: 0.7467411545623835 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 208, 'learning_rate': 0.010675910461732434, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 2}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-06-30 13:31:18,607] Trial 8 finished with value: 0.6908752327746742 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 218, 'learning_rate': 0.09877357270779337, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-06-30 13:31:18,632] Trial 9 finished with value: 0.6983240223463687 and parameters: {'classifier': 'SVM', 'C': 68.84324411838249, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-06-30 13:31:19,942] Trial 10 finished with value: 0.7579143389199254 and parameters: {'classifier': 'RandomForest', 'n_estimators': 293, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-06-30 13:31:19,968] Trial 11 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2715812773509733, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7858472998137803.
[I 2026-06-30 13:31:19,994] Trial 12 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.181778746181603, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 12 with value: 0.7877094972067038.
[I 2026-06-30 13:31:20,017] Trial 13 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1439145425667094, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:20,039] Trial 14 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10974781792071941, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:21,274] Trial 15 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:21,310] Trial 16 finished with value: 0.7337057728119181 and parameters: {'classifier': 'SVM', 'C': 0.7706873944916321, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:21,348] Trial 17 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8962973209884657, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:21,380] Trial 18 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11205127219957808, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:21,794] Trial 19 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 52, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:21,831] Trial 20 finished with value: 0.7355679702048418 and parameters: {'classifier': 'SVM', 'C': 0.6966967620939742, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:21,862] Trial 21 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11744592074139855, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:21,893] Trial 22 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10195665920312744, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:21,926] Trial 23 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.35399961391896984, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:21,968] Trial 24 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.30788069814598007, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:22,016] Trial 25 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.10024910947261018, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:23,607] Trial 26 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 259, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:23,654] Trial 27 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.027540037312366, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:23,689] Trial 28 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2520062906280211, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:23,728] Trial 29 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5739831383174684, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:24,497] Trial 30 finished with value: 0.7560521415270017 and parameters: {'classifier': 'RandomForest', 'n_estimators': 160, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:24,519] Trial 31 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16990648779562204, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:24,541] Trial 32 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.20179694688184338, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:24,562] Trial 33 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16089555225013535, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:24,585] Trial 34 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.3331139738848936, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:24,614] Trial 35 finished with value: 0.7225325884543762 and parameters: {'classifier': 'SVM', 'C': 2.0921053195981054, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:25,866] Trial 36 finished with value: 0.6927374301675977 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 162, 'learning_rate': 0.2691605636586613, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:25,895] Trial 37 finished with value: 0.7541899441340782 and parameters: {'classifier': 'SVM', 'C': 0.16225770851422752, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:25,920] Trial 38 finished with value: 0.7374301675977654 and parameters: {'classifier': 'SVM', 'C': 0.4067139676472262, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:26,326] Trial 39 finished with value: 0.74487895716946 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 51, 'learning_rate': 0.010139130188680042, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 9}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:26,353] Trial 40 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1627709972391245, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:26,374] Trial 41 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10371072522684469, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:26,395] Trial 42 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10747489007669014, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:26,417] Trial 43 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16570506961893294, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:26,440] Trial 44 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.22581652148863554, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:29,952] Trial 45 finished with value: 0.7281191806331471 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 251, 'learning_rate': 0.027925793480671632, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 5}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:29,987] Trial 46 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4709352559087501, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:30,009] Trial 47 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13572251934078117, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:30,596] Trial 48 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 135, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:30,638] Trial 49 finished with value: 0.7392923649906891 and parameters: {'classifier': 'SVM', 'C': 25.329004046997667, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:32,003] Trial 50 finished with value: 0.7281191806331471 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 80, 'learning_rate': 0.033508156340124426, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:32,036] Trial 51 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13752446406031305, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:32,059] Trial 52 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.15520645929407742, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:32,082] Trial 53 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2188895107189733, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:32,105] Trial 54 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13672493455000728, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:32,138] Trial 55 finished with value: 0.7765363128491621 and parameters: {'classifier': 'SVM', 'C': 0.13637837707066675, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:32,162] Trial 56 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.273462073009504, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:32,189] Trial 57 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13049213058767517, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:32,215] Trial 58 finished with value: 0.7188081936685289 and parameters: {'classifier': 'SVM', 'C': 0.2235520177313845, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:33,167] Trial 59 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 244, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:33,196] Trial 60 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.1366515038513707, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:33,218] Trial 61 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14965988444607134, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:33,240] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1279242645730461, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:33,262] Trial 63 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1291338647369149, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:33,285] Trial 64 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10124151297155334, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:33,309] Trial 65 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.30112174098094363, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:33,332] Trial 66 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2062222395245602, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:33,361] Trial 67 finished with value: 0.7467411545623835 and parameters: {'classifier': 'SVM', 'C': 0.12728433591415747, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:33,388] Trial 68 finished with value: 0.696461824953445 and parameters: {'classifier': 'SVM', 'C': 88.88255922353683, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:34,520] Trial 69 finished with value: 0.7579143389199254 and parameters: {'classifier': 'RandomForest', 'n_estimators': 180, 'max_depth': 18, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:34,557] Trial 70 finished with value: 0.7392923649906891 and parameters: {'classifier': 'SVM', 'C': 0.461034552582347, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:34,589] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13795147138253108, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:34,621] Trial 72 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.18831199280263475, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:34,653] Trial 73 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2629923165028555, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:34,694] Trial 74 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12409395713066469, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:34,726] Trial 75 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10116936309747332, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:36,931] Trial 76 finished with value: 0.7467411545623835 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 132, 'learning_rate': 0.26981141876078457, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:36,956] Trial 77 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.18679487335572698, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:36,982] Trial 78 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.3548136924093806, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:37,009] Trial 79 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15148343456836022, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.
[I 2026-06-30 13:31:37,032] Trial 80 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.25323924689137833, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7895716945996275.

In [28]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.1439145425667094, 'kernel': 'linear', 'gamma': 'auto'}
Best trial accuracy: 0.7895716945996275

In [29]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.761639,2026-06-30 13:30:59.488663,2026-06-30 13:31:00.609067,0 days 00:00:01.120404,NaN,NaN,GradientBoosting,NaN,NaN,0.155279,3.0,3.0,10.0,114.0,COMPLETE
1,1,0.750466,2026-06-30 13:31:00.610521,2026-06-30 13:31:03.780620,0 days 00:00:03.170099,NaN,NaN,GradientBoosting,NaN,NaN,0.077194,9.0,7.0,5.0,162.0,COMPLETE
2,2,0.735568,2026-06-30 13:31:03.783418,2026-06-30 13:31:08.026674,0 days 00:00:04.243256,NaN,NaN,GradientBoosting,NaN,NaN,0.099923,16.0,7.0,4.0,208.0,COMPLETE
3,3,0.744879,2026-06-30 13:31:08.028008,2026-06-30 13:31:09.897248,0 days 00:00:01.869240,NaN,NaN,GradientBoosting,NaN,NaN,0.026921,9.0,4.0,7.0,110.0,COMPLETE
4,4,0.785847,2026-06-30 13:31:09.899644,2026-06-30 13:31:10.001880,0 days 00:00:00.102236,12.969653,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.787709,2026-06-30 13:31:39.395705,2026-06-30 13:31:39.417635,0 days 00:00:00.021930,0.172465,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.713222,2026-06-30 13:31:39.418301,2026-06-30 13:31:39.442087,0 days 00:00:00.023786,0.144967,NaN,SVM,auto,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.785847,2026-06-30 13:31:39.442754,2026-06-30 13:31:39.464384,0 days 00:00:00.021630,0.274365,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.789572,2026-06-30 13:31:39.465115,2026-06-30 13:31:39.487178,0 days 00:00:00.022063,0.115948,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.785847,2026-06-30 13:31:39.487852,2026-06-30 13:31:39.515913,0 days 00:00:00.028061,0.188640,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [30]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 78
GradientBoosting    13
RandomForest         9
Name: count, dtype: int64

In [31]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.736714
RandomForest        0.764329
SVM                 0.775939
Name: value, dtype: float64

In [32]:
# 1. Optimization History
plot_optimization_history(study).show()

In [33]:
# 3. Slice Plot
plot_slice(study).show()

In [34]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [36]:
! pip install optuna-integration[xgboost]

Collecting optuna-integration[xgboost]
  Downloading optuna_integration-4.9.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (4.9.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (3.2.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.50)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.0.3)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (2.28.9)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (1.16.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[xgboost]) (3.5.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna->optuna-integration[xgboost]) (3.0.3)
Downloading optuna_integration-4.9.0-py3-none-any.whl (103 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.4/103.4 kB 5.0 MB/s eta 0:00:00
Installing collected packages: optuna-integration
Successfully installed optuna-integration-4.9.0

In [41]:
# ==========================================================
# Optuna + XGBoost Hyperparameter Tuning Example
# Dataset : Iris
# ==========================================================

# Install Optuna integration (Run once)
!pip install -q optuna-integration[xgboost]

# -------------------------
# Import Libraries
# -------------------------
import optuna
import xgboost as xgb
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# ----------------------------------------------------------
# STEP 1 : Load Dataset
# ----------------------------------------------------------
# X -> Features
# y -> Labels (0,1,2)

X, y = load_iris(return_X_y=True)

print("Dataset Shape :", X.shape)

# ----------------------------------------------------------
# STEP 2 : Split Dataset
# ----------------------------------------------------------
# 80% Training
# 20% Testing

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# ----------------------------------------------------------
# STEP 3 : Objective Function
# ----------------------------------------------------------
# Optuna calls this function once for every trial.
# Every trial uses DIFFERENT hyperparameters.

def objective(trial):

    # ------------------------------------------------------
    # Hyperparameter Search Space
    # Optuna will automatically choose values
    # ------------------------------------------------------

    params = {

        # Suppress training logs
        "verbosity": 0,

        # Multi-class classification
        "objective": "multi:softprob",

        # Number of classes
        "num_class": 3,

        # Validation metric
        "eval_metric": "mlogloss",

        # Tree based booster
        "booster": "gbtree",

        # L2 Regularization
        "lambda": trial.suggest_float(
            "lambda",
            1e-8,
            1.0,
            log=True
        ),

        # L1 Regularization
        "alpha": trial.suggest_float(
            "alpha",
            1e-8,
            1.0,
            log=True
        ),

        # Learning Rate
        "eta": trial.suggest_float(
            "eta",
            0.01,
            0.30
        ),

        # Minimum loss reduction
        "gamma": trial.suggest_float(
            "gamma",
            1e-8,
            1.0,
            log=True
        ),

        # Maximum depth of tree
        "max_depth": trial.suggest_int(
            "max_depth",
            3,
            9
        ),

        # Minimum child weight
        "min_child_weight": trial.suggest_int(
            "min_child_weight",
            1,
            10
        ),

        # Fraction of rows used
        "subsample": trial.suggest_float(
            "subsample",
            0.4,
            1.0
        ),

        # Fraction of columns used
        "colsample_bytree": trial.suggest_float(
            "colsample_bytree",
            0.4,
            1.0
        )
    }

    # ------------------------------------------------------
    # Convert Dataset to DMatrix
    # DMatrix is XGBoost's optimized data structure
    # ------------------------------------------------------

    dtrain = xgb.DMatrix(
        X_train,
        label=y_train
    )

    dtest = xgb.DMatrix(
        X_test,
        label=y_test
    )

    # ------------------------------------------------------
    # Pruning Callback
    # Stops bad trials early
    # ------------------------------------------------------

    pruning_callback = optuna.integration.XGBoostPruningCallback(
        trial,
        "eval-mlogloss"
    )

    # ------------------------------------------------------
    # Train XGBoost
    # ------------------------------------------------------

    model = xgb.train(

        params,

        dtrain,

        # Maximum number of trees
        num_boost_round=300,

        # Evaluation datasets
        evals=[
            (dtrain, "train"),
            (dtest, "eval")
        ],

        # Stop if validation loss
        # doesn't improve for 30 rounds
        early_stopping_rounds=30,

        # Enable pruning
        callbacks=[pruning_callback]
    )

    # ------------------------------------------------------
    # Prediction
    # ------------------------------------------------------

    predictions = model.predict(dtest)

    # Convert probabilities to class labels
    predicted_labels = np.argmax(
        predictions,
        axis=1
    )

    # ------------------------------------------------------
    # Accuracy
    # ------------------------------------------------------

    accuracy = accuracy_score(
        y_test,
        predicted_labels
    )

    # Return accuracy to Optuna
    return accuracy


# ----------------------------------------------------------
# STEP 4 : Create Study
# ----------------------------------------------------------
# maximize -> Highest Accuracy
# Pruner -> Stops poor trials early

study = optuna.create_study(

    direction="maximize",

    pruner=optuna.pruners.SuccessiveHalvingPruner()
)

# ----------------------------------------------------------
# STEP 5 : Start Optimization
# ----------------------------------------------------------

study.optimize(
    objective,
    n_trials=50
)

# ----------------------------------------------------------
# STEP 6 : Best Result
# ----------------------------------------------------------

print("\n===============================")
print("BEST HYPERPARAMETERS")
print("===============================")

for key, value in study.best_trial.params.items():
    print(f"{key:20} : {value}")

print("\n===============================")
print("BEST ACCURACY")
print("===============================")

print(study.best_value)

[I 2026-06-30 13:48:10,274] A new study created in memory with name: no-name-4a55af2f-c471-43f8-a348-d7d00b1cd536

Dataset Shape : (150, 4)
[0]	train-mlogloss:1.00193	eval-mlogloss:1.01011
[1]	train-mlogloss:0.80266	eval-mlogloss:0.79417
[2]	train-mlogloss:0.65897	eval-mlogloss:0.63540
[3]	train-mlogloss:0.57459	eval-mlogloss:0.53715
[4]	train-mlogloss:0.49990	eval-mlogloss:0.45821
[5]	train-mlogloss:0.42708	eval-mlogloss:0.38136
[6]	train-mlogloss:0.38186	eval-mlogloss:0.33566
[7]	train-mlogloss:0.35470	eval-mlogloss:0.31750
[8]	train-mlogloss:0.31543	eval-mlogloss:0.27087
[9]	train-mlogloss:0.28803	eval-mlogloss:0.24258
[10]	train-mlogloss:0.27376	eval-mlogloss:0.22281
[11]	train-mlogloss:0.26476	eval-mlogloss:0.21091
[12]	train-mlogloss:0.25994	eval-mlogloss:0.20852
[13]	train-mlogloss:0.25213	eval-mlogloss:0.19840
[14]	train-mlogloss:0.25182	eval-mlogloss:0.19735
[15]	train-mlogloss:0.25107	eval-mlogloss:0.19649
[16]	train-mlogloss:0.24168	eval-mlogloss:0.18334
[17]	train-mlogloss:0.24148	eval-mlogloss:0.18231
[18]	train-mlogloss:0.24143	eval-mlogloss:0.18226
[19]	train-mlogloss:0.24083	eval-mlogloss:0.18256
[20]	train-mlogloss:0.24062	eval-mlogloss:0.18169
[21]	train-mlogloss:0.24038	eval-mlogloss:0.18149
[22]	train-mlogloss:0.23434	eval-mlogloss:0.17194
[23]	train-mlogloss:0.22863	eval-mlogloss:0.16307
[24]	train-mlogloss:0.22806	eval-mlogloss:0.16264
[25]	train-mlogloss:0.22274	eval-mlogloss:0.15721
[26]	train-mlogloss:0.22243	eval-mlogloss:0.15662
[27]	train-mlogloss:0.22144	eval-mlogloss:0.15599
[28]	train-mlogloss:0.22141	eval-mlogloss:0.15607
[29]	train-mlogloss:0.22134	eval-mlogloss:0.15619
[30]	train-mlogloss:0.22162	eval-mlogloss:0.15712
[31]	train-mlogloss:0.22129	eval-mlogloss:0.15618
[32]	train-mlogloss:0.22109	eval-mlogloss:0.15586
[33]	train-mlogloss:0.22091	eval-mlogloss:0.15561
[34]	train-mlogloss:0.22003	eval-mlogloss:0.15477
[35]	train-mlogloss:0.21914	eval-mlogloss:0.15442
[36]	train-mlogloss:0.21935	eval-mlogloss:0.15454
[37]	train-mlogloss:0.21889	eval-mlogloss:0.15573
[38]	train-mlogloss:0.21888	eval-mlogloss:0.15574
[39]	train-mlogloss:0.21871	eval-mlogloss:0.15572
[40]	train-mlogloss:0.21857	eval-mlogloss:0.15495
[41]	train-mlogloss:0.21761	eval-mlogloss:0.15351
[42]	train-mlogloss:0.21746	eval-mlogloss:0.15249
[43]	train-mlogloss:0.21779	eval-mlogloss:0.15273
[44]	train-mlogloss:0.21766	eval-mlogloss:0.15270
[45]	train-mlogloss:0.21679	eval-mlogloss:0.15192
[46]	train-mlogloss:0.21680	eval-mlogloss:0.15227
[47]	train-mlogloss:0.21669	eval-mlogloss:0.15193
[48]	train-mlogloss:0.21599	eval-mlogloss:0.15107
[49]	train-mlogloss:0.21530	eval-mlogloss:0.15003
[50]	train-mlogloss:0.21009	eval-mlogloss:0.14297
[51]	train-mlogloss:0.21017	eval-mlogloss:0.14303
[52]	train-mlogloss:0.21021	eval-mlogloss:0.14301
[53]	train-mlogloss:0.21030	eval-mlogloss:0.14296
[54]	train-mlogloss:0.21014	eval-mlogloss:0.14267
[55]	train-mlogloss:0.20998	eval-mlogloss:0.14227
[56]	train-mlogloss:0.20990	eval-mlogloss:0.14199
[57]	train-mlogloss:0.21001	eval-mlogloss:0.14165
[58]	train-mlogloss:0.21005	eval-mlogloss:0.14164
[59]	train-mlogloss:0.20921	eval-mlogloss:0.14099
[60]	train-mlogloss:0.20873	eval-mlogloss:0.14083
[61]	train-mlogloss:0.20872	eval-mlogloss:0.14103
[62]	train-mlogloss:0.20844	eval-mlogloss:0.13981
[63]	train-mlogloss:0.20833	eval-mlogloss:0.13948
[64]	train-mlogloss:0.20829	eval-mlogloss:0.13947
[65]	train-mlogloss:0.20864	eval-mlogloss:0.13982
[66]	train-mlogloss:0.20821	eval-mlogloss:0.13952
[67]	train-mlogloss:0.20817	eval-mlogloss:0.13978
[68]	train-mlogloss:0.20790	eval-mlogloss:0.13962
[69]	train-mlogloss:0.20754	eval-mlogloss:0.13936
[70]	train-mlogloss:0.20756	eval-mlogloss:0.13924
[71]	train-mlogloss:0.20765	eval-mlogloss:0.13920
[72]	train-mlogloss:0.20763	eval-mlogloss:0.13901
[73]	train-mlogloss:0.20767	eval-mlogloss:0.13893
[74]	train-mlogloss:0.20774	eval-mlogloss:0.13920
[75]	train-mlogloss:0.20789	eval-mlogloss:0.13942
[76]	train-mlogloss:0.20794	eval-mlogloss:0.13954
[77]	train-mlogloss:0.20791	eval-mlogloss:0.14029
[78]	train-mlogloss:0.20813	eval-mlogloss:0.14053
[79]	train-mlogloss:0.20812	eval-mlogloss:0.14062
[80]	train-mlogloss:0.20764	eval-mlogloss:0.14039
[81]	train-mlogloss:0.20751	eval-mlogloss:0.14053
[82]	train-mlogloss:0.20738	eval-mlogloss:0.14051
[83]	train-mlogloss:0.20741	eval-mlogloss:0.14037
[84]	train-mlogloss:0.20744	eval-mlogloss:0.14042
[85]	train-mlogloss:0.20726	eval-mlogloss:0.14023
[86]	train-mlogloss:0.20727	eval-mlogloss:0.14037
[87]	train-mlogloss:0.20727	eval-mlogloss:0.14033
[88]	train-mlogloss:0.20645	eval-mlogloss:0.13961
[89]	train-mlogloss:0.20627	eval-mlogloss:0.13942
[90]	train-mlogloss:0.20625	eval-mlogloss:0.13938
[91]	train-mlogloss:0.20656	eval-mlogloss:0.13933
[92]	train-mlogloss:0.20646	eval-mlogloss:0.13925
[93]	train-mlogloss:0.20607	eval-mlogloss:0.13734
[94]	train-mlogloss:0.20609	eval-mlogloss:0.13734
[95]	train-mlogloss:0.20636	eval-mlogloss:0.13777
[96]	train-mlogloss:0.20647	eval-mlogloss:0.13791
[97]	train-mlogloss:0.20647	eval-mlogloss:0.13844
[98]	train-mlogloss:0.20707	eval-mlogloss:0.13891
[99]	train-mlogloss:0.20533	eval-mlogloss:0.13927
[100]	train-mlogloss:0.20509	eval-mlogloss:0.13894
[101]	train-mlogloss:0.20463	eval-mlogloss:0.13867
[102]	train-mlogloss:0.20464	eval-mlogloss:0.13882
[103]	train-mlogloss:0.20464	eval-mlogloss:0.13881
[104]	train-mlogloss:0.20409	eval-mlogloss:0.13822
[105]	train-mlogloss:0.20374	eval-mlogloss:0.13778
[106]	train-mlogloss:0.20365	eval-mlogloss:0.13814
[107]	train-mlogloss:0.20390	eval-mlogloss:0.13877
[108]	train-mlogloss:0.20343	eval-mlogloss:0.13832
[109]	train-mlogloss:0.20318	eval-mlogloss:0.13794
[110]	train-mlogloss:0.20322	eval-mlogloss:0.13806
[111]	train-mlogloss:0.20325	eval-mlogloss:0.13802
[112]	train-mlogloss:0.20308	eval-mlogloss:0.13785
[113]	train-mlogloss:0.20308	eval-mlogloss:0.13781
[114]	train-mlogloss:0.20311	eval-mlogloss:0.13789
[115]	train-mlogloss:0.20288	eval-mlogloss:0.13732
[116]	train-mlogloss:0.20307	eval-mlogloss:0.13724
[117]	train-mlogloss:0.20269	eval-mlogloss:0.13589
[118]	train-mlogloss:0.20262	eval-mlogloss:0.13592
[119]	train-mlogloss:0.20259	eval-mlogloss:0.13567
[120]	train-mlogloss:0.20266	eval-mlogloss:0.13552
[121]	train-mlogloss:0.20228	eval-mlogloss:0.13542
[122]	train-mlogloss:0.20226	eval-mlogloss:0.13563
[123]	train-mlogloss:0.20236	eval-mlogloss:0.13559
[124]	train-mlogloss:0.20233	eval-mlogloss:0.13527
[125]	train-mlogloss:0.20221	eval-mlogloss:0.13513
[126]	train-mlogloss:0.20223	eval-mlogloss:0.13536
[127]	train-mlogloss:0.20251	eval-mlogloss:0.13518
[128]	train-mlogloss:0.20245	eval-mlogloss:0.13457
[129]	train-mlogloss:0.20194	eval-mlogloss:0.13451
[130]	train-mlogloss:0.20225	eval-mlogloss:0.13478
[131]	train-mlogloss:0.20226	eval-mlogloss:0.13505
[132]	train-mlogloss:0.20182	eval-mlogloss:0.13442
[133]	train-mlogloss:0.20176	eval-mlogloss:0.13419
[134]	train-mlogloss:0.20175	eval-mlogloss:0.13427
[135]	train-mlogloss:0.20192	eval-mlogloss:0.13462
[136]	train-mlogloss:0.20201	eval-mlogloss:0.13476
[137]	train-mlogloss:0.20200	eval-mlogloss:0.13466
[138]	train-mlogloss:0.20191	eval-mlogloss:0.13480
[139]	train-mlogloss:0.20202	eval-mlogloss:0.13473
[140]	train-mlogloss:0.20196	eval-mlogloss:0.13473
[141]	train-mlogloss:0.20202	eval-mlogloss:0.13493
[142]	train-mlogloss:0.20237	eval-mlogloss:0.13520
[143]	train-mlogloss:0.20226	eval-mlogloss:0.13533
[144]	train-mlogloss:0.20176	eval-mlogloss:0.13505
[145]	train-mlogloss:0.20190	eval-mlogloss:0.13538
[146]	train-mlogloss:0.20174	eval-mlogloss:0.13495
[147]	train-mlogloss:0.20163	eval-mlogloss:0.13475
[148]	train-mlogloss:0.20168	eval-mlogloss:0.13503
[149]	train-mlogloss:0.20167	eval-mlogloss:0.13496
[150]	train-mlogloss:0.20158	eval-mlogloss:0.13440
[151]	train-mlogloss:0.20158	eval-mlogloss:0.13439
[152]	train-mlogloss:0.20160	eval-mlogloss:0.13423
[153]	train-mlogloss:0.20155	eval-mlogloss:0.13427
[154]	train-mlogloss:0.20181	eval-mlogloss:0.13382
[155]	train-mlogloss:0.20188	eval-mlogloss:0.13379
[156]	train-mlogloss:0.20198	eval-mlogloss:0.13372
[157]	train-mlogloss:0.20191	eval-mlogloss:0.13376
[158]	train-mlogloss:0.20172	eval-mlogloss:0.13390
[159]	train-mlogloss:0.20142	eval-mlogloss:0.13376
[160]	train-mlogloss:0.20146	eval-mlogloss:0.13381
[161]	train-mlogloss:0.20130	eval-mlogloss:0.13415
[162]	train-mlogloss:0.20142	eval-mlogloss:0.13458
[163]	train-mlogloss:0.20147	eval-mlogloss:0.13486
[164]	train-mlogloss:0.20124	eval-mlogloss:0.13464
[165]	train-mlogloss:0.20127	eval-mlogloss:0.13456
[166]	train-mlogloss:0.20123	eval-mlogloss:0.13483
[167]	train-mlogloss:0.20118	eval-mlogloss:0.13482
[168]	train-mlogloss:0.20118	eval-mlogloss:0.13503
[169]	train-mlogloss:0.20062	eval-mlogloss:0.13457
[170]	train-mlogloss:0.20066	eval-mlogloss:0.13471
[171]	train-mlogloss:0.20068	eval-mlogloss:0.13487
[172]	train-mlogloss:0.20057	eval-mlogloss:0.13501
[173]	train-mlogloss:0.20058	eval-mlogloss:0.13500
[174]	train-mlogloss:0.20083	eval-mlogloss:0.13555
[175]	train-mlogloss:0.20073	eval-mlogloss:0.13515
[176]	train-mlogloss:0.20067	eval-mlogloss:0.13488
[177]	train-mlogloss:0.20047	eval-mlogloss:0.13419
[178]	train-mlogloss:0.20031	eval-mlogloss:0.13426
[179]	train-mlogloss:0.20046	eval-mlogloss:0.13406
[180]	train-mlogloss:0.20088	eval-mlogloss:0.13428
[181]	train-mlogloss:0.20053	eval-mlogloss:0.13414
[182]	train-mlogloss:0.20041	eval-mlogloss:0.13374
[183]	train-mlogloss:0.20044	eval-mlogloss:0.13413
[184]	train-mlogloss:0.20031	eval-mlogloss:0.13321
[185]	train-mlogloss:0.20034	eval-mlogloss:0.13325
[186]	train-mlogloss:0.20043	eval-mlogloss:0.13288
[187]	train-mlogloss:0.20055	eval-mlogloss:0.13268
[188]	train-mlogloss:0.20042	eval-mlogloss:0.13309
[189]	train-mlogloss:0.20037	eval-mlogloss:0.13344
[190]	train-mlogloss:0.20032	eval-mlogloss:0.13379
[191]	train-mlogloss:0.20012	eval-mlogloss:0.13337
[192]	train-mlogloss:0.20013	eval-mlogloss:0.13368
[193]	train-mlogloss:0.19995	eval-mlogloss:0.13337
[194]	train-mlogloss:0.19999	eval-mlogloss:0.13358
[195]	train-mlogloss:0.19998	eval-mlogloss:0.13314
[196]	train-mlogloss:0.19991	eval-mlogloss:0.13282
[197]	train-mlogloss:0.19986	eval-mlogloss:0.13285
[198]	train-mlogloss:0.20016	eval-mlogloss:0.13279
[199]	train-mlogloss:0.20023	eval-mlogloss:0.13283
[200]	train-mlogloss:0.20005	eval-mlogloss:0.13273
[201]	train-mlogloss:0.20020	eval-mlogloss:0.13258
[202]	train-mlogloss:0.19999	eval-mlogloss:0.13233
[203]	train-mlogloss:0.19996	eval-mlogloss:0.13242
[204]	train-mlogloss:0.19982	eval-mlogloss:0.13219
[205]	train-mlogloss:0.19987	eval-mlogloss:0.13209
[206]	train-mlogloss:0.19982	eval-mlogloss:0.13245
[207]	train-mlogloss:0.19981	eval-mlogloss:0.13225
[208]	train-mlogloss:0.19983	eval-mlogloss:0.13262
[209]	train-mlogloss:0.20019	eval-mlogloss:0.13248
[210]	train-mlogloss:0.20001	eval-mlogloss:0.13227
[211]	train-mlogloss:0.19989	eval-mlogloss:0.13226
[212]	train-mlogloss:0.19979	eval-mlogloss:0.13227
[213]	train-mlogloss:0.19980	eval-mlogloss:0.13223
[214]	train-mlogloss:0.19995	eval-mlogloss:0.13203
[215]	train-mlogloss:0.19971	eval-mlogloss:0.13223
[216]	train-mlogloss:0.19975	eval-mlogloss:0.13212
[217]	train-mlogloss:0.19976	eval-mlogloss:0.13234
[218]	train-mlogloss:0.19986	eval-mlogloss:0.13272
[219]	train-mlogloss:0.19993	eval-mlogloss:0.13259
[220]	train-mlogloss:0.19967	eval-mlogloss:0.13234
[221]	train-mlogloss:0.19972	eval-mlogloss:0.13273
[222]	train-mlogloss:0.19953	eval-mlogloss:0.13181
[223]	train-mlogloss:0.19943	eval-mlogloss:0.13116
[224]	train-mlogloss:0.19930	eval-mlogloss:0.13120
[225]	train-mlogloss:0.19931	eval-mlogloss:0.13138
[226]	train-mlogloss:0.19927	eval-mlogloss:0.13075
[227]	train-mlogloss:0.19926	eval-mlogloss:0.13096
[228]	train-mlogloss:0.19921	eval-mlogloss:0.13094
[229]	train-mlogloss:0.19938	eval-mlogloss:0.13138
[230]	train-mlogloss:0.19934	eval-mlogloss:0.13131
[231]	train-mlogloss:0.19939	eval-mlogloss:0.13119
[232]	train-mlogloss:0.19924	eval-mlogloss:0.13117
[233]	train-mlogloss:0.19916	eval-mlogloss:0.13092
[234]	train-mlogloss:0.19932	eval-mlogloss:0.13161
[235]	train-mlogloss:0.19939	eval-mlogloss:0.13170
[236]	train-mlogloss:0.19951	eval-mlogloss:0.13226
[237]	train-mlogloss:0.19952	eval-mlogloss:0.13231
[238]	train-mlogloss:0.19952	eval-mlogloss:0.13248
[239]	train-mlogloss:0.19935	eval-mlogloss:0.13220
[240]	train-mlogloss:0.19941	eval-mlogloss:0.13243
[241]	train-mlogloss:0.19921	eval-mlogloss:0.13211
[242]	train-mlogloss:0.19931	eval-mlogloss:0.13243
[243]	train-mlogloss:0.19925	eval-mlogloss:0.13224
[244]	train-mlogloss:0.19921	eval-mlogloss:0.13210
[245]	train-mlogloss:0.19923	eval-mlogloss:0.13206
[246]	train-mlogloss:0.19926	eval-mlogloss:0.13157
[247]	train-mlogloss:0.19919	eval-mlogloss:0.13140
[248]	train-mlogloss:0.19919	eval-mlogloss:0.13138
[249]	train-mlogloss:0.19925	eval-mlogloss:0.13138
[250]	train-mlogloss:0.19930	eval-mlogloss:0.13113
[251]	train-mlogloss:0.19933	eval-mlogloss:0.13110
[252]	train-mlogloss:0.19951	eval-mlogloss:0.13078
[253]	train-mlogloss:0.19947	eval-mlogloss:0.13085
[254]	train-mlogloss:0.19924	eval-mlogloss:0.13097
[255]	train-mlogloss:0.19918	eval-mlogloss:0.13107
[256]	train-mlogloss:0.19918	eval-mlogloss:0.13107

[I 2026-06-30 13:48:11,230] Trial 0 finished with value: 1.0 and parameters: {'lambda': 5.983901338203304e-08, 'alpha': 9.1113450684657e-06, 'eta': 0.1940290447101199, 'gamma': 5.809704739686863e-05, 'max_depth': 4, 'min_child_weight': 6, 'subsample': 0.5320212572787584, 'colsample_bytree': 0.4497509937016343}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.90085	eval-mlogloss:0.88696
[1]	train-mlogloss:0.75400	eval-mlogloss:0.72758
[2]	train-mlogloss:0.63727	eval-mlogloss:0.60413
[3]	train-mlogloss:0.54317	eval-mlogloss:0.50744
[4]	train-mlogloss:0.46964	eval-mlogloss:0.43119
[5]	train-mlogloss:0.40834	eval-mlogloss:0.36358
[6]	train-mlogloss:0.35882	eval-mlogloss:0.31198
[7]	train-mlogloss:0.31927	eval-mlogloss:0.27047
[8]	train-mlogloss:0.28771	eval-mlogloss:0.23413
[9]	train-mlogloss:0.26351	eval-mlogloss:0.20905
[10]	train-mlogloss:0.24449	eval-mlogloss:0.18898
[11]	train-mlogloss:0.23031	eval-mlogloss:0.17258
[12]	train-mlogloss:0.21659	eval-mlogloss:0.15604
[13]	train-mlogloss:0.21159	eval-mlogloss:0.14913
[14]	train-mlogloss:0.20839	eval-mlogloss:0.14550
[15]	train-mlogloss:0.20705	eval-mlogloss:0.14380
[16]	train-mlogloss:0.20585	eval-mlogloss:0.14210
[17]	train-mlogloss:0.20410	eval-mlogloss:0.14014
[18]	train-mlogloss:0.20329	eval-mlogloss:0.14133
[19]	train-mlogloss:0.20160	eval-mlogloss:0.13921
[20]	train-mlogloss:0.20143	eval-mlogloss:0.13850
[21]	train-mlogloss:0.20107	eval-mlogloss:0.13686
[22]	train-mlogloss:0.20012	eval-mlogloss:0.13587
[23]	train-mlogloss:0.19580	eval-mlogloss:0.13055
[24]	train-mlogloss:0.19529	eval-mlogloss:0.13026
[25]	train-mlogloss:0.19479	eval-mlogloss:0.12999
[26]	train-mlogloss:0.19454	eval-mlogloss:0.12905
[27]	train-mlogloss:0.19428	eval-mlogloss:0.12878
[28]	train-mlogloss:0.19386	eval-mlogloss:0.12838
[29]	train-mlogloss:0.19369	eval-mlogloss:0.12768
[30]	train-mlogloss:0.19093	eval-mlogloss:0.12431
[31]	train-mlogloss:0.19062	eval-mlogloss:0.12422
[32]	train-mlogloss:0.19042	eval-mlogloss:0.12408
[33]	train-mlogloss:0.19023	eval-mlogloss:0.12264
[34]	train-mlogloss:0.19012	eval-mlogloss:0.12214
[35]	train-mlogloss:0.18995	eval-mlogloss:0.12198
[36]	train-mlogloss:0.18972	eval-mlogloss:0.12183
[37]	train-mlogloss:0.18955	eval-mlogloss:0.12045
[38]	train-mlogloss:0.18947	eval-mlogloss:0.12021
[39]	train-mlogloss:0.18899	eval-mlogloss:0.11957
[40]	train-mlogloss:0.18880	eval-mlogloss:0.11947
[41]	train-mlogloss:0.18852	eval-mlogloss:0.11943
[42]	train-mlogloss:0.18839	eval-mlogloss:0.11881
[43]	train-mlogloss:0.18605	eval-mlogloss:0.11574
[44]	train-mlogloss:0.18590	eval-mlogloss:0.11559
[45]	train-mlogloss:0.18565	eval-mlogloss:0.11552
[46]	train-mlogloss:0.18558	eval-mlogloss:0.11572
[47]	train-mlogloss:0.18546	eval-mlogloss:0.11565
[48]	train-mlogloss:0.18548	eval-mlogloss:0.11561
[49]	train-mlogloss:0.18541	eval-mlogloss:0.11500
[50]	train-mlogloss:0.18539	eval-mlogloss:0.11496
[51]	train-mlogloss:0.18532	eval-mlogloss:0.11525
[52]	train-mlogloss:0.18508	eval-mlogloss:0.11516
[53]	train-mlogloss:0.18503	eval-mlogloss:0.11533
[54]	train-mlogloss:0.18501	eval-mlogloss:0.11511
[55]	train-mlogloss:0.18468	eval-mlogloss:0.11493
[56]	train-mlogloss:0.18465	eval-mlogloss:0.11485
[57]	train-mlogloss:0.18467	eval-mlogloss:0.11480
[58]	train-mlogloss:0.18469	eval-mlogloss:0.11477
[59]	train-mlogloss:0.18440	eval-mlogloss:0.11465
[60]	train-mlogloss:0.18438	eval-mlogloss:0.11471
[61]	train-mlogloss:0.18412	eval-mlogloss:0.11461
[62]	train-mlogloss:0.18401	eval-mlogloss:0.11457
[63]	train-mlogloss:0.18405	eval-mlogloss:0.11453
[64]	train-mlogloss:0.18402	eval-mlogloss:0.11396
[65]	train-mlogloss:0.18404	eval-mlogloss:0.11412
[66]	train-mlogloss:0.18392	eval-mlogloss:0.11434
[67]	train-mlogloss:0.18395	eval-mlogloss:0.11430
[68]	train-mlogloss:0.18371	eval-mlogloss:0.11428
[69]	train-mlogloss:0.18358	eval-mlogloss:0.11420
[70]	train-mlogloss:0.18356	eval-mlogloss:0.11413
[71]	train-mlogloss:0.18353	eval-mlogloss:0.11328
[72]	train-mlogloss:0.18349	eval-mlogloss:0.11324
[73]	train-mlogloss:0.18349	eval-mlogloss:0.11327
[74]	train-mlogloss:0.18337	eval-mlogloss:0.11342
[75]	train-mlogloss:0.18330	eval-mlogloss:0.11345
[76]	train-mlogloss:0.18330	eval-mlogloss:0.11362
[77]	train-mlogloss:0.18323	eval-mlogloss:0.11361
[78]	train-mlogloss:0.18347	eval-mlogloss:0.11402
[79]	train-mlogloss:0.18337	eval-mlogloss:0.11404
[80]	train-mlogloss:0.18315	eval-mlogloss:0.11392
[81]	train-mlogloss:0.18314	eval-mlogloss:0.11401
[82]	train-mlogloss:0.18309	eval-mlogloss:0.11393
[83]	train-mlogloss:0.18269	eval-mlogloss:0.11332
[84]	train-mlogloss:0.18234	eval-mlogloss:0.11277
[85]	train-mlogloss:0.18229	eval-mlogloss:0.11263
[86]	train-mlogloss:0.18221	eval-mlogloss:0.11248
[87]	train-mlogloss:0.18209	eval-mlogloss:0.11242
[88]	train-mlogloss:0.18197	eval-mlogloss:0.11231
[89]	train-mlogloss:0.18181	eval-mlogloss:0.11222
[90]	train-mlogloss:0.18176	eval-mlogloss:0.11218
[91]	train-mlogloss:0.18174	eval-mlogloss:0.11218
[92]	train-mlogloss:0.18154	eval-mlogloss:0.11199
[93]	train-mlogloss:0.18153	eval-mlogloss:0.11187
[94]	train-mlogloss:0.18157	eval-mlogloss:0.11211
[95]	train-mlogloss:0.18160	eval-mlogloss:0.11212
[96]	train-mlogloss:0.18158	eval-mlogloss:0.11181
[97]	train-mlogloss:0.18143	eval-mlogloss:0.11176
[98]	train-mlogloss:0.18145	eval-mlogloss:0.11179
[99]	train-mlogloss:0.18135	eval-mlogloss:0.11188
[100]	train-mlogloss:0.18137	eval-mlogloss:0.11188
[101]	train-mlogloss:0.18123	eval-mlogloss:0.11187
[102]	train-mlogloss:0.18122	eval-mlogloss:0.11189
[103]	train-mlogloss:0.18118	eval-mlogloss:0.11169
[104]	train-mlogloss:0.18114	eval-mlogloss:0.11180
[105]	train-mlogloss:0.18105	eval-mlogloss:0.11175
[106]	train-mlogloss:0.18097	eval-mlogloss:0.11169
[107]	train-mlogloss:0.18083	eval-mlogloss:0.11172
[108]	train-mlogloss:0.18080	eval-mlogloss:0.11172
[109]	train-mlogloss:0.18070	eval-mlogloss:0.11161
[110]	train-mlogloss:0.18064	eval-mlogloss:0.11161
[111]	train-mlogloss:0.18056	eval-mlogloss:0.11150
[112]	train-mlogloss:0.18053	eval-mlogloss:0.11145
[113]	train-mlogloss:0.18054	eval-mlogloss:0.11147
[114]	train-mlogloss:0.18048	eval-mlogloss:0.11148
[115]	train-mlogloss:0.18051	eval-mlogloss:0.11153
[116]	train-mlogloss:0.18037	eval-mlogloss:0.11145
[117]	train-mlogloss:0.18035	eval-mlogloss:0.11132
[118]	train-mlogloss:0.18032	eval-mlogloss:0.11132
[119]	train-mlogloss:0.18027	eval-mlogloss:0.11126
[120]	train-mlogloss:0.18028	eval-mlogloss:0.11124
[121]	train-mlogloss:0.18025	eval-mlogloss:0.11130
[122]	train-mlogloss:0.18027	eval-mlogloss:0.11137
[123]	train-mlogloss:0.18021	eval-mlogloss:0.11143
[124]	train-mlogloss:0.18011	eval-mlogloss:0.11134
[125]	train-mlogloss:0.18010	eval-mlogloss:0.11131
[126]	train-mlogloss:0.18006	eval-mlogloss:0.11145
[127]	train-mlogloss:0.17999	eval-mlogloss:0.11132
[128]	train-mlogloss:0.18001	eval-mlogloss:0.11150
[129]	train-mlogloss:0.17999	eval-mlogloss:0.11155
[130]	train-mlogloss:0.17994	eval-mlogloss:0.11151
[131]	train-mlogloss:0.17995	eval-mlogloss:0.11158
[132]	train-mlogloss:0.17991	eval-mlogloss:0.11143
[133]	train-mlogloss:0.17991	eval-mlogloss:0.11146
[134]	train-mlogloss:0.17993	eval-mlogloss:0.11156
[135]	train-mlogloss:0.17986	eval-mlogloss:0.11153
[136]	train-mlogloss:0.17986	eval-mlogloss:0.11150
[137]	train-mlogloss:0.17958	eval-mlogloss:0.11127
[138]	train-mlogloss:0.17953	eval-mlogloss:0.11127
[139]	train-mlogloss:0.17944	eval-mlogloss:0.11119
[140]	train-mlogloss:0.17944	eval-mlogloss:0.11117
[141]	train-mlogloss:0.17943	eval-mlogloss:0.11125
[142]	train-mlogloss:0.17948	eval-mlogloss:0.11135
[143]	train-mlogloss:0.17949	eval-mlogloss:0.11135
[144]	train-mlogloss:0.17951	eval-mlogloss:0.11141
[145]	train-mlogloss:0.17957	eval-mlogloss:0.11152
[146]	train-mlogloss:0.17943	eval-mlogloss:0.11133
[147]	train-mlogloss:0.17934	eval-mlogloss:0.11080
[148]	train-mlogloss:0.17933	eval-mlogloss:0.11082
[149]	train-mlogloss:0.17939	eval-mlogloss:0.11093
[150]	train-mlogloss:0.17932	eval-mlogloss:0.11077
[151]	train-mlogloss:0.17930	eval-mlogloss:0.11062
[152]	train-mlogloss:0.17919	eval-mlogloss:0.11065
[153]	train-mlogloss:0.17916	eval-mlogloss:0.11075
[154]	train-mlogloss:0.17914	eval-mlogloss:0.11059
[155]	train-mlogloss:0.17908	eval-mlogloss:0.11078
[156]	train-mlogloss:0.17912	eval-mlogloss:0.11073
[157]	train-mlogloss:0.17910	eval-mlogloss:0.11074
[158]	train-mlogloss:0.17909	eval-mlogloss:0.11066
[159]	train-mlogloss:0.17892	eval-mlogloss:0.11056
[160]	train-mlogloss:0.17879	eval-mlogloss:0.11044
[161]	train-mlogloss:0.17876	eval-mlogloss:0.11044
[162]	train-mlogloss:0.17872	eval-mlogloss:0.11054
[163]	train-mlogloss:0.17873	eval-mlogloss:0.11061
[164]	train-mlogloss:0.17879	eval-mlogloss:0.11074
[165]	train-mlogloss:0.17869	eval-mlogloss:0.11062
[166]	train-mlogloss:0.17863	eval-mlogloss:0.11057
[167]	train-mlogloss:0.17860	eval-mlogloss:0.11054
[168]	train-mlogloss:0.17859	eval-mlogloss:0.11049
[169]	train-mlogloss:0.17850	eval-mlogloss:0.11037
[170]	train-mlogloss:0.17848	eval-mlogloss:0.11034
[171]	train-mlogloss:0.17842	eval-mlogloss:0.11036
[172]	train-mlogloss:0.17842	eval-mlogloss:0.11031
[173]	train-mlogloss:0.17841	eval-mlogloss:0.11033
[174]	train-mlogloss:0.17844	eval-mlogloss:0.11065
[175]	train-mlogloss:0.17842	eval-mlogloss:0.11059
[176]	train-mlogloss:0.17848	eval-mlogloss:0.11056
[177]	train-mlogloss:0.17847	eval-mlogloss:0.11041
[178]	train-mlogloss:0.17842	eval-mlogloss:0.11038
[179]	train-mlogloss:0.17843	eval-mlogloss:0.11037
[180]	train-mlogloss:0.17846	eval-mlogloss:0.11043
[181]	train-mlogloss:0.17844	eval-mlogloss:0.11044
[182]	train-mlogloss:0.17837	eval-mlogloss:0.11040
[183]	train-mlogloss:0.17834	eval-mlogloss:0.11040
[184]	train-mlogloss:0.17831	eval-mlogloss:0.11049
[185]	train-mlogloss:0.17830	eval-mlogloss:0.11058
[186]	train-mlogloss:0.17821	eval-mlogloss:0.11053
[187]	train-mlogloss:0.17822	eval-mlogloss:0.11052
[188]	train-mlogloss:0.17821	eval-mlogloss:0.11055
[189]	train-mlogloss:0.17821	eval-mlogloss:0.11056
[190]	train-mlogloss:0.17814	eval-mlogloss:0.11056
[191]	train-mlogloss:0.17814	eval-mlogloss:0.11060
[192]	train-mlogloss:0.17815	eval-mlogloss:0.11056
[193]	train-mlogloss:0.17816	eval-mlogloss:0.11055
[194]	train-mlogloss:0.17818	eval-mlogloss:0.11065
[195]	train-mlogloss:0.17816	eval-mlogloss:0.11076
[196]	train-mlogloss:0.17805	eval-mlogloss:0.11077
[197]	train-mlogloss:0.17804	eval-mlogloss:0.11069
[198]	train-mlogloss:0.17802	eval-mlogloss:0.11064
[199]	train-mlogloss:0.17800	eval-mlogloss:0.11075
[200]	train-mlogloss:0.17803	eval-mlogloss:0.11071
[201]	train-mlogloss:0.17808	eval-mlogloss:0.11063
[202]	train-mlogloss:0.17807	eval-mlogloss:0.11060

[I 2026-06-30 13:48:11,691] Trial 1 finished with value: 1.0 and parameters: {'lambda': 2.5356403236317053e-07, 'alpha': 0.02734270886469923, 'eta': 0.16149675429930996, 'gamma': 0.0001776204519139857, 'max_depth': 6, 'min_child_weight': 8, 'subsample': 0.8169598095746593, 'colsample_bytree': 0.7659033867137852}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.90697	eval-mlogloss:0.89658
[1]	train-mlogloss:0.79117	eval-mlogloss:0.76567
[2]	train-mlogloss:0.68974	eval-mlogloss:0.65986
[3]	train-mlogloss:0.58234	eval-mlogloss:0.54743
[4]	train-mlogloss:0.51413	eval-mlogloss:0.47333
[5]	train-mlogloss:0.45747	eval-mlogloss:0.41694
[6]	train-mlogloss:0.41597	eval-mlogloss:0.37024
[7]	train-mlogloss:0.39730	eval-mlogloss:0.35057
[8]	train-mlogloss:0.36603	eval-mlogloss:0.31660
[9]	train-mlogloss:0.34892	eval-mlogloss:0.29740
[10]	train-mlogloss:0.33662	eval-mlogloss:0.28279
[11]	train-mlogloss:0.32724	eval-mlogloss:0.27338
[12]	train-mlogloss:0.31232	eval-mlogloss:0.25837
[13]	train-mlogloss:0.31193	eval-mlogloss:0.25809
[14]	train-mlogloss:0.31149	eval-mlogloss:0.25866
[15]	train-mlogloss:0.31093	eval-mlogloss:0.25785
[16]	train-mlogloss:0.30960	eval-mlogloss:0.25411
[17]	train-mlogloss:0.30895	eval-mlogloss:0.25490
[18]	train-mlogloss:0.29980	eval-mlogloss:0.24448
[19]	train-mlogloss:0.29896	eval-mlogloss:0.24333
[20]	train-mlogloss:0.29906	eval-mlogloss:0.24345
[21]	train-mlogloss:0.29906	eval-mlogloss:0.24337
[22]	train-mlogloss:0.29804	eval-mlogloss:0.24017
[23]	train-mlogloss:0.29813	eval-mlogloss:0.24028
[24]	train-mlogloss:0.29779	eval-mlogloss:0.23943
[25]	train-mlogloss:0.28844	eval-mlogloss:0.22776
[26]	train-mlogloss:0.28828	eval-mlogloss:0.22743
[27]	train-mlogloss:0.28829	eval-mlogloss:0.22752
[28]	train-mlogloss:0.28777	eval-mlogloss:0.22749
[29]	train-mlogloss:0.28772	eval-mlogloss:0.22754
[30]	train-mlogloss:0.28720	eval-mlogloss:0.22769
[31]	train-mlogloss:0.28630	eval-mlogloss:0.22651
[32]	train-mlogloss:0.28584	eval-mlogloss:0.22636
[33]	train-mlogloss:0.28568	eval-mlogloss:0.22589
[34]	train-mlogloss:0.28538	eval-mlogloss:0.22525
[35]	train-mlogloss:0.28505	eval-mlogloss:0.22542
[36]	train-mlogloss:0.28511	eval-mlogloss:0.22548
[37]	train-mlogloss:0.28428	eval-mlogloss:0.22591
[38]	train-mlogloss:0.28428	eval-mlogloss:0.22610
[39]	train-mlogloss:0.28431	eval-mlogloss:0.22621
[40]	train-mlogloss:0.28380	eval-mlogloss:0.22604
[41]	train-mlogloss:0.28351	eval-mlogloss:0.22597
[42]	train-mlogloss:0.28296	eval-mlogloss:0.22403
[43]	train-mlogloss:0.28320	eval-mlogloss:0.22461
[44]	train-mlogloss:0.28310	eval-mlogloss:0.22443
[45]	train-mlogloss:0.28282	eval-mlogloss:0.22407
[46]	train-mlogloss:0.28285	eval-mlogloss:0.22363
[47]	train-mlogloss:0.28223	eval-mlogloss:0.22335
[48]	train-mlogloss:0.28207	eval-mlogloss:0.22268
[49]	train-mlogloss:0.28187	eval-mlogloss:0.22151
[50]	train-mlogloss:0.27498	eval-mlogloss:0.21204
[51]	train-mlogloss:0.27492	eval-mlogloss:0.21229
[52]	train-mlogloss:0.27499	eval-mlogloss:0.21240
[53]	train-mlogloss:0.27506	eval-mlogloss:0.21245
[54]	train-mlogloss:0.27485	eval-mlogloss:0.21180
[55]	train-mlogloss:0.27452	eval-mlogloss:0.21164
[56]	train-mlogloss:0.27423	eval-mlogloss:0.21080
[57]	train-mlogloss:0.27433	eval-mlogloss:0.21081
[58]	train-mlogloss:0.27437	eval-mlogloss:0.21091
[59]	train-mlogloss:0.27415	eval-mlogloss:0.21059
[60]	train-mlogloss:0.27395	eval-mlogloss:0.21044
[61]	train-mlogloss:0.27355	eval-mlogloss:0.21014
[62]	train-mlogloss:0.27367	eval-mlogloss:0.20985
[63]	train-mlogloss:0.27364	eval-mlogloss:0.20957
[64]	train-mlogloss:0.27357	eval-mlogloss:0.20948
[65]	train-mlogloss:0.27382	eval-mlogloss:0.21021
[66]	train-mlogloss:0.27357	eval-mlogloss:0.20985
[67]	train-mlogloss:0.27379	eval-mlogloss:0.21042
[68]	train-mlogloss:0.27356	eval-mlogloss:0.21063
[69]	train-mlogloss:0.27339	eval-mlogloss:0.21016
[70]	train-mlogloss:0.27325	eval-mlogloss:0.21006
[71]	train-mlogloss:0.27331	eval-mlogloss:0.21029
[72]	train-mlogloss:0.27330	eval-mlogloss:0.21006
[73]	train-mlogloss:0.27291	eval-mlogloss:0.20981
[74]	train-mlogloss:0.27291	eval-mlogloss:0.21000
[75]	train-mlogloss:0.27301	eval-mlogloss:0.21022
[76]	train-mlogloss:0.27244	eval-mlogloss:0.20970
[77]	train-mlogloss:0.27222	eval-mlogloss:0.20966
[78]	train-mlogloss:0.27244	eval-mlogloss:0.21025
[79]	train-mlogloss:0.27243	eval-mlogloss:0.21030
[80]	train-mlogloss:0.27237	eval-mlogloss:0.21019
[81]	train-mlogloss:0.27231	eval-mlogloss:0.21019
[82]	train-mlogloss:0.27221	eval-mlogloss:0.20999
[83]	train-mlogloss:0.27219	eval-mlogloss:0.20984
[84]	train-mlogloss:0.27198	eval-mlogloss:0.20992
[85]	train-mlogloss:0.27185	eval-mlogloss:0.20959
[86]	train-mlogloss:0.27183	eval-mlogloss:0.20962
[87]	train-mlogloss:0.27157	eval-mlogloss:0.20944
[88]	train-mlogloss:0.27136	eval-mlogloss:0.20934
[89]	train-mlogloss:0.27130	eval-mlogloss:0.20912
[90]	train-mlogloss:0.27144	eval-mlogloss:0.20946
[91]	train-mlogloss:0.27176	eval-mlogloss:0.20973
[92]	train-mlogloss:0.27160	eval-mlogloss:0.20939
[93]	train-mlogloss:0.27135	eval-mlogloss:0.20875
[94]	train-mlogloss:0.27142	eval-mlogloss:0.20892
[95]	train-mlogloss:0.27158	eval-mlogloss:0.20940
[96]	train-mlogloss:0.27111	eval-mlogloss:0.20904
[97]	train-mlogloss:0.27089	eval-mlogloss:0.20843
[98]	train-mlogloss:0.27119	eval-mlogloss:0.20902
[99]	train-mlogloss:0.27096	eval-mlogloss:0.20846
[100]	train-mlogloss:0.27089	eval-mlogloss:0.20817
[101]	train-mlogloss:0.27052	eval-mlogloss:0.20764
[102]	train-mlogloss:0.27053	eval-mlogloss:0.20776
[103]	train-mlogloss:0.27059	eval-mlogloss:0.20797
[104]	train-mlogloss:0.27048	eval-mlogloss:0.20802
[105]	train-mlogloss:0.27024	eval-mlogloss:0.20733
[106]	train-mlogloss:0.27013	eval-mlogloss:0.20781
[107]	train-mlogloss:0.27034	eval-mlogloss:0.20842
[108]	train-mlogloss:0.26981	eval-mlogloss:0.20786
[109]	train-mlogloss:0.26967	eval-mlogloss:0.20785
[110]	train-mlogloss:0.26971	eval-mlogloss:0.20804
[111]	train-mlogloss:0.26962	eval-mlogloss:0.20792
[112]	train-mlogloss:0.26954	eval-mlogloss:0.20753
[113]	train-mlogloss:0.26956	eval-mlogloss:0.20751
[114]	train-mlogloss:0.26957	eval-mlogloss:0.20757
[115]	train-mlogloss:0.26935	eval-mlogloss:0.20806
[116]	train-mlogloss:0.26911	eval-mlogloss:0.20792
[117]	train-mlogloss:0.26892	eval-mlogloss:0.20836
[118]	train-mlogloss:0.26886	eval-mlogloss:0.20817
[119]	train-mlogloss:0.26874	eval-mlogloss:0.20802
[120]	train-mlogloss:0.26865	eval-mlogloss:0.20843
[121]	train-mlogloss:0.26879	eval-mlogloss:0.20918
[122]	train-mlogloss:0.26876	eval-mlogloss:0.20924
[123]	train-mlogloss:0.26869	eval-mlogloss:0.20866
[124]	train-mlogloss:0.26218	eval-mlogloss:0.20123
[125]	train-mlogloss:0.26207	eval-mlogloss:0.20156
[126]	train-mlogloss:0.26190	eval-mlogloss:0.20060
[127]	train-mlogloss:0.26202	eval-mlogloss:0.20074
[128]	train-mlogloss:0.26168	eval-mlogloss:0.20048
[129]	train-mlogloss:0.26151	eval-mlogloss:0.20019
[130]	train-mlogloss:0.26178	eval-mlogloss:0.20074
[131]	train-mlogloss:0.26176	eval-mlogloss:0.20078
[132]	train-mlogloss:0.26148	eval-mlogloss:0.20015
[133]	train-mlogloss:0.26144	eval-mlogloss:0.19996
[134]	train-mlogloss:0.26141	eval-mlogloss:0.19990
[135]	train-mlogloss:0.26111	eval-mlogloss:0.20012
[136]	train-mlogloss:0.26117	eval-mlogloss:0.20027
[137]	train-mlogloss:0.26118	eval-mlogloss:0.20027
[138]	train-mlogloss:0.26096	eval-mlogloss:0.19994
[139]	train-mlogloss:0.26105	eval-mlogloss:0.20003
[140]	train-mlogloss:0.26098	eval-mlogloss:0.19993
[141]	train-mlogloss:0.26104	eval-mlogloss:0.19992
[142]	train-mlogloss:0.26119	eval-mlogloss:0.20039
[143]	train-mlogloss:0.26125	eval-mlogloss:0.20053
[144]	train-mlogloss:0.26096	eval-mlogloss:0.20017
[145]	train-mlogloss:0.26105	eval-mlogloss:0.20042
[146]	train-mlogloss:0.26089	eval-mlogloss:0.20001
[147]	train-mlogloss:0.26084	eval-mlogloss:0.20006
[148]	train-mlogloss:0.26090	eval-mlogloss:0.20021
[149]	train-mlogloss:0.26089	eval-mlogloss:0.20021
[150]	train-mlogloss:0.26079	eval-mlogloss:0.19982
[151]	train-mlogloss:0.26078	eval-mlogloss:0.19976
[152]	train-mlogloss:0.26085	eval-mlogloss:0.19991
[153]	train-mlogloss:0.26084	eval-mlogloss:0.19978
[154]	train-mlogloss:0.26099	eval-mlogloss:0.19950
[155]	train-mlogloss:0.26106	eval-mlogloss:0.19965
[156]	train-mlogloss:0.26114	eval-mlogloss:0.19982
[157]	train-mlogloss:0.26112	eval-mlogloss:0.19972
[158]	train-mlogloss:0.26096	eval-mlogloss:0.19974
[159]	train-mlogloss:0.26084	eval-mlogloss:0.19962
[160]	train-mlogloss:0.26087	eval-mlogloss:0.19949
[161]	train-mlogloss:0.26077	eval-mlogloss:0.19913
[162]	train-mlogloss:0.26086	eval-mlogloss:0.19905
[163]	train-mlogloss:0.26090	eval-mlogloss:0.19912
[164]	train-mlogloss:0.26076	eval-mlogloss:0.19939
[165]	train-mlogloss:0.26056	eval-mlogloss:0.19909
[166]	train-mlogloss:0.26064	eval-mlogloss:0.19962
[167]	train-mlogloss:0.26061	eval-mlogloss:0.19971
[168]	train-mlogloss:0.26060	eval-mlogloss:0.19992
[169]	train-mlogloss:0.26062	eval-mlogloss:0.20001
[170]	train-mlogloss:0.26064	eval-mlogloss:0.20012
[171]	train-mlogloss:0.26026	eval-mlogloss:0.19994
[172]	train-mlogloss:0.26004	eval-mlogloss:0.19949
[173]	train-mlogloss:0.26001	eval-mlogloss:0.19941
[174]	train-mlogloss:0.26007	eval-mlogloss:0.19986
[175]	train-mlogloss:0.25999	eval-mlogloss:0.19967
[176]	train-mlogloss:0.25994	eval-mlogloss:0.19947
[177]	train-mlogloss:0.25966	eval-mlogloss:0.19922
[178]	train-mlogloss:0.25975	eval-mlogloss:0.19971
[179]	train-mlogloss:0.25991	eval-mlogloss:0.19999
[180]	train-mlogloss:0.26006	eval-mlogloss:0.19899
[181]	train-mlogloss:0.25979	eval-mlogloss:0.19863
[182]	train-mlogloss:0.25972	eval-mlogloss:0.19829
[183]	train-mlogloss:0.25977	eval-mlogloss:0.19860
[184]	train-mlogloss:0.25965	eval-mlogloss:0.19879
[185]	train-mlogloss:0.25967	eval-mlogloss:0.19879
[186]	train-mlogloss:0.25956	eval-mlogloss:0.19795
[187]	train-mlogloss:0.25965	eval-mlogloss:0.19777
[188]	train-mlogloss:0.25955	eval-mlogloss:0.19809
[189]	train-mlogloss:0.25951	eval-mlogloss:0.19826
[190]	train-mlogloss:0.25957	eval-mlogloss:0.19856
[191]	train-mlogloss:0.25948	eval-mlogloss:0.19824
[192]	train-mlogloss:0.25944	eval-mlogloss:0.19830
[193]	train-mlogloss:0.25936	eval-mlogloss:0.19801
[194]	train-mlogloss:0.25912	eval-mlogloss:0.19779
[195]	train-mlogloss:0.25917	eval-mlogloss:0.19774
[196]	train-mlogloss:0.25920	eval-mlogloss:0.19773
[197]	train-mlogloss:0.25910	eval-mlogloss:0.19746
[198]	train-mlogloss:0.25912	eval-mlogloss:0.19728
[199]	train-mlogloss:0.25911	eval-mlogloss:0.19706
[200]	train-mlogloss:0.25913	eval-mlogloss:0.19704
[201]	train-mlogloss:0.25926	eval-mlogloss:0.19697
[202]	train-mlogloss:0.25918	eval-mlogloss:0.19703
[203]	train-mlogloss:0.25916	eval-mlogloss:0.19707
[204]	train-mlogloss:0.25915	eval-mlogloss:0.19703
[205]	train-mlogloss:0.25920	eval-mlogloss:0.19707
[206]	train-mlogloss:0.25909	eval-mlogloss:0.19696
[207]	train-mlogloss:0.25912	eval-mlogloss:0.19704
[208]	train-mlogloss:0.25909	eval-mlogloss:0.19692
[209]	train-mlogloss:0.25920	eval-mlogloss:0.19710
[210]	train-mlogloss:0.25914	eval-mlogloss:0.19718
[211]	train-mlogloss:0.25886	eval-mlogloss:0.19715
[212]	train-mlogloss:0.25884	eval-mlogloss:0.19736
[213]	train-mlogloss:0.25884	eval-mlogloss:0.19731
[214]	train-mlogloss:0.25898	eval-mlogloss:0.19712
[215]	train-mlogloss:0.25885	eval-mlogloss:0.19726
[216]	train-mlogloss:0.25893	eval-mlogloss:0.19715
[217]	train-mlogloss:0.25892	eval-mlogloss:0.19741
[218]	train-mlogloss:0.25887	eval-mlogloss:0.19763
[219]	train-mlogloss:0.25895	eval-mlogloss:0.19769
[220]	train-mlogloss:0.25890	eval-mlogloss:0.19769
[221]	train-mlogloss:0.25891	eval-mlogloss:0.19794
[222]	train-mlogloss:0.25887	eval-mlogloss:0.19785
[223]	train-mlogloss:0.25886	eval-mlogloss:0.19783
[224]	train-mlogloss:0.25879	eval-mlogloss:0.19732
[225]	train-mlogloss:0.25882	eval-mlogloss:0.19724
[226]	train-mlogloss:0.25877	eval-mlogloss:0.19684
[227]	train-mlogloss:0.25876	eval-mlogloss:0.19707
[228]	train-mlogloss:0.25876	eval-mlogloss:0.19708
[229]	train-mlogloss:0.25887	eval-mlogloss:0.19762
[230]	train-mlogloss:0.25891	eval-mlogloss:0.19771
[231]	train-mlogloss:0.25898	eval-mlogloss:0.19787
[232]	train-mlogloss:0.25887	eval-mlogloss:0.19761
[233]	train-mlogloss:0.25880	eval-mlogloss:0.19735
[234]	train-mlogloss:0.25889	eval-mlogloss:0.19769
[235]	train-mlogloss:0.25894	eval-mlogloss:0.19785
[236]	train-mlogloss:0.25898	eval-mlogloss:0.19794
[237]	train-mlogloss:0.25898	eval-mlogloss:0.19794
[238]	train-mlogloss:0.25899	eval-mlogloss:0.19794
[239]	train-mlogloss:0.25884	eval-mlogloss:0.19749
[240]	train-mlogloss:0.25889	eval-mlogloss:0.19755
[241]	train-mlogloss:0.25876	eval-mlogloss:0.19747
[242]	train-mlogloss:0.25883	eval-mlogloss:0.19776
[243]	train-mlogloss:0.25878	eval-mlogloss:0.19754
[244]	train-mlogloss:0.25875	eval-mlogloss:0.19756
[245]	train-mlogloss:0.25877	eval-mlogloss:0.19744
[246]	train-mlogloss:0.25877	eval-mlogloss:0.19698
[247]	train-mlogloss:0.25871	eval-mlogloss:0.19708
[248]	train-mlogloss:0.25871	eval-mlogloss:0.19707
[249]	train-mlogloss:0.25878	eval-mlogloss:0.19693
[250]	train-mlogloss:0.25881	eval-mlogloss:0.19697
[251]	train-mlogloss:0.25887	eval-mlogloss:0.19698
[252]	train-mlogloss:0.25897	eval-mlogloss:0.19686
[253]	train-mlogloss:0.25894	eval-mlogloss:0.19683
[254]	train-mlogloss:0.25876	eval-mlogloss:0.19693
[255]	train-mlogloss:0.25866	eval-mlogloss:0.19704
[256]	train-mlogloss:0.25865	eval-mlogloss:0.19701
[257]	train-mlogloss:0.25863	eval-mlogloss:0.19696
[258]	train-mlogloss:0.25880	eval-mlogloss:0.19680
[259]	train-mlogloss:0.25883	eval-mlogloss:0.19684
[260]	train-mlogloss:0.25896	eval-mlogloss:0.19673
[261]	train-mlogloss:0.25887	eval-mlogloss:0.19676
[262]	train-mlogloss:0.25861	eval-mlogloss:0.19657
[263]	train-mlogloss:0.25831	eval-mlogloss:0.19635
[264]	train-mlogloss:0.25843	eval-mlogloss:0.19655
[265]	train-mlogloss:0.25835	eval-mlogloss:0.19666
[266]	train-mlogloss:0.25839	eval-mlogloss:0.19683
[267]	train-mlogloss:0.25838	eval-mlogloss:0.19691
[268]	train-mlogloss:0.25838	eval-mlogloss:0.19687
[269]	train-mlogloss:0.25820	eval-mlogloss:0.19681
[270]	train-mlogloss:0.25822	eval-mlogloss:0.19671
[271]	train-mlogloss:0.25821	eval-mlogloss:0.19687
[272]	train-mlogloss:0.25821	eval-mlogloss:0.19685
[273]	train-mlogloss:0.25822	eval-mlogloss:0.19691
[274]	train-mlogloss:0.25824	eval-mlogloss:0.19708
[275]	train-mlogloss:0.25829	eval-mlogloss:0.19723
[276]	train-mlogloss:0.25826	eval-mlogloss:0.19696
[277]	train-mlogloss:0.25825	eval-mlogloss:0.19709
[278]	train-mlogloss:0.25825	eval-mlogloss:0.19687
[279]	train-mlogloss:0.25823	eval-mlogloss:0.19677
[280]	train-mlogloss:0.25820	eval-mlogloss:0.19648
[281]	train-mlogloss:0.25818	eval-mlogloss:0.19657
[282]	train-mlogloss:0.25828	eval-mlogloss:0.19694
[283]	train-mlogloss:0.25829	eval-mlogloss:0.19679
[284]	train-mlogloss:0.25825	eval-mlogloss:0.19681
[285]	train-mlogloss:0.25826	eval-mlogloss:0.19709
[286]	train-mlogloss:0.25805	eval-mlogloss:0.19729
[287]	train-mlogloss:0.25803	eval-mlogloss:0.19687
[288]	train-mlogloss:0.25801	eval-mlogloss:0.19670
[289]	train-mlogloss:0.25791	eval-mlogloss:0.19673
[290]	train-mlogloss:0.25789	eval-mlogloss:0.19691
[291]	train-mlogloss:0.25792	eval-mlogloss:0.19714
[292]	train-mlogloss:0.25792	eval-mlogloss:0.19713
[293]	train-mlogloss:0.25796	eval-mlogloss:0.19731

[I 2026-06-30 13:48:12,396] Trial 2 finished with value: 1.0 and parameters: {'lambda': 1.34910211539594e-05, 'alpha': 7.994548292143824e-06, 'eta': 0.16038737588536725, 'gamma': 5.032791735853532e-05, 'max_depth': 7, 'min_child_weight': 8, 'subsample': 0.5307427974883131, 'colsample_bytree': 0.8354343207989766}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.96534	eval-mlogloss:0.95639
[1]	train-mlogloss:0.85149	eval-mlogloss:0.83822
[2]	train-mlogloss:0.75206	eval-mlogloss:0.73844
[3]	train-mlogloss:0.66962	eval-mlogloss:0.65146
[4]	train-mlogloss:0.59802	eval-mlogloss:0.57890
[5]	train-mlogloss:0.53469	eval-mlogloss:0.51325
[6]	train-mlogloss:0.48006	eval-mlogloss:0.45595
[7]	train-mlogloss:0.43524	eval-mlogloss:0.40996
[8]	train-mlogloss:0.39657	eval-mlogloss:0.37003
[9]	train-mlogloss:0.36095	eval-mlogloss:0.33258
[10]	train-mlogloss:0.32868	eval-mlogloss:0.30385
[11]	train-mlogloss:0.30125	eval-mlogloss:0.27345
[12]	train-mlogloss:0.27700	eval-mlogloss:0.25053
[13]	train-mlogloss:0.25607	eval-mlogloss:0.22731
[14]	train-mlogloss:0.23633	eval-mlogloss:0.20593
[15]	train-mlogloss:0.21850	eval-mlogloss:0.18635
[16]	train-mlogloss:0.20319	eval-mlogloss:0.16913
[17]	train-mlogloss:0.18918	eval-mlogloss:0.15319
[18]	train-mlogloss:0.17510	eval-mlogloss:0.13934
[19]	train-mlogloss:0.16223	eval-mlogloss:0.12855
[20]	train-mlogloss:0.14879	eval-mlogloss:0.11814
[21]	train-mlogloss:0.13954	eval-mlogloss:0.10688
[22]	train-mlogloss:0.13077	eval-mlogloss:0.09724
[23]	train-mlogloss:0.12251	eval-mlogloss:0.08857
[24]	train-mlogloss:0.11464	eval-mlogloss:0.08110
[25]	train-mlogloss:0.10797	eval-mlogloss:0.07449
[26]	train-mlogloss:0.10216	eval-mlogloss:0.06832
[27]	train-mlogloss:0.09710	eval-mlogloss:0.06551
[28]	train-mlogloss:0.09157	eval-mlogloss:0.06067
[29]	train-mlogloss:0.08591	eval-mlogloss:0.05597
[30]	train-mlogloss:0.08179	eval-mlogloss:0.05265
[31]	train-mlogloss:0.07790	eval-mlogloss:0.04926

[I 2026-06-30 13:48:12,483] Trial 3 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:0.98071	eval-mlogloss:0.97650
[1]	train-mlogloss:0.89067	eval-mlogloss:0.87003
[2]	train-mlogloss:0.82194	eval-mlogloss:0.80283
[3]	train-mlogloss:0.74988	eval-mlogloss:0.72679
[4]	train-mlogloss:0.69208	eval-mlogloss:0.66362
[5]	train-mlogloss:0.63571	eval-mlogloss:0.60604
[6]	train-mlogloss:0.58580	eval-mlogloss:0.55160
[7]	train-mlogloss:0.56152	eval-mlogloss:0.52595
[8]	train-mlogloss:0.52132	eval-mlogloss:0.48367
[9]	train-mlogloss:0.48840	eval-mlogloss:0.44863
[10]	train-mlogloss:0.47352	eval-mlogloss:0.43053
[11]	train-mlogloss:0.46034	eval-mlogloss:0.41296
[12]	train-mlogloss:0.44005	eval-mlogloss:0.39331
[13]	train-mlogloss:0.43921	eval-mlogloss:0.39234
[14]	train-mlogloss:0.43785	eval-mlogloss:0.38956
[15]	train-mlogloss:0.43630	eval-mlogloss:0.38701
[16]	train-mlogloss:0.43404	eval-mlogloss:0.38189
[17]	train-mlogloss:0.43316	eval-mlogloss:0.38284
[18]	train-mlogloss:0.42090	eval-mlogloss:0.36725
[19]	train-mlogloss:0.41943	eval-mlogloss:0.36545
[20]	train-mlogloss:0.40712	eval-mlogloss:0.35290
[21]	train-mlogloss:0.40580	eval-mlogloss:0.34887
[22]	train-mlogloss:0.40353	eval-mlogloss:0.34792
[23]	train-mlogloss:0.38313	eval-mlogloss:0.32611
[24]	train-mlogloss:0.38250	eval-mlogloss:0.32503
[25]	train-mlogloss:0.37270	eval-mlogloss:0.31264
[26]	train-mlogloss:0.37254	eval-mlogloss:0.31244
[27]	train-mlogloss:0.37251	eval-mlogloss:0.31257
[28]	train-mlogloss:0.37245	eval-mlogloss:0.31288
[29]	train-mlogloss:0.37238	eval-mlogloss:0.31314
[30]	train-mlogloss:0.37162	eval-mlogloss:0.31318
[31]	train-mlogloss:0.37033	eval-mlogloss:0.31164
[32]	train-mlogloss:0.36982	eval-mlogloss:0.31166
[33]	train-mlogloss:0.36969	eval-mlogloss:0.31087
[34]	train-mlogloss:0.36931	eval-mlogloss:0.31018
[35]	train-mlogloss:0.36929	eval-mlogloss:0.31045
[36]	train-mlogloss:0.36966	eval-mlogloss:0.31069
[37]	train-mlogloss:0.36965	eval-mlogloss:0.31007
[38]	train-mlogloss:0.36964	eval-mlogloss:0.31023
[39]	train-mlogloss:0.36923	eval-mlogloss:0.30998
[40]	train-mlogloss:0.36839	eval-mlogloss:0.30974
[41]	train-mlogloss:0.36785	eval-mlogloss:0.30957
[42]	train-mlogloss:0.36704	eval-mlogloss:0.30712
[43]	train-mlogloss:0.36694	eval-mlogloss:0.30773
[44]	train-mlogloss:0.36686	eval-mlogloss:0.30772
[45]	train-mlogloss:0.36637	eval-mlogloss:0.30725
[46]	train-mlogloss:0.36651	eval-mlogloss:0.30665
[47]	train-mlogloss:0.36613	eval-mlogloss:0.30583
[48]	train-mlogloss:0.36579	eval-mlogloss:0.30476
[49]	train-mlogloss:0.36485	eval-mlogloss:0.30437
[50]	train-mlogloss:0.35715	eval-mlogloss:0.29449
[51]	train-mlogloss:0.35693	eval-mlogloss:0.29486
[52]	train-mlogloss:0.35698	eval-mlogloss:0.29478
[53]	train-mlogloss:0.35684	eval-mlogloss:0.29453
[54]	train-mlogloss:0.35662	eval-mlogloss:0.29395
[55]	train-mlogloss:0.35606	eval-mlogloss:0.29362
[56]	train-mlogloss:0.35566	eval-mlogloss:0.29274
[57]	train-mlogloss:0.35534	eval-mlogloss:0.29085
[58]	train-mlogloss:0.35536	eval-mlogloss:0.29097
[59]	train-mlogloss:0.35489	eval-mlogloss:0.29083
[60]	train-mlogloss:0.35470	eval-mlogloss:0.29090
[61]	train-mlogloss:0.35412	eval-mlogloss:0.29067
[62]	train-mlogloss:0.35405	eval-mlogloss:0.29046
[63]	train-mlogloss:0.35408	eval-mlogloss:0.29011
[64]	train-mlogloss:0.35400	eval-mlogloss:0.29009
[65]	train-mlogloss:0.35416	eval-mlogloss:0.29100
[66]	train-mlogloss:0.35421	eval-mlogloss:0.29077
[67]	train-mlogloss:0.35412	eval-mlogloss:0.29070
[68]	train-mlogloss:0.35370	eval-mlogloss:0.29009
[69]	train-mlogloss:0.35339	eval-mlogloss:0.28942
[70]	train-mlogloss:0.35328	eval-mlogloss:0.28954
[71]	train-mlogloss:0.35312	eval-mlogloss:0.29012
[72]	train-mlogloss:0.35309	eval-mlogloss:0.28981
[73]	train-mlogloss:0.35261	eval-mlogloss:0.28944
[74]	train-mlogloss:0.35231	eval-mlogloss:0.29026
[75]	train-mlogloss:0.35220	eval-mlogloss:0.29052
[76]	train-mlogloss:0.35117	eval-mlogloss:0.28970
[77]	train-mlogloss:0.35082	eval-mlogloss:0.28972
[78]	train-mlogloss:0.35037	eval-mlogloss:0.29015
[79]	train-mlogloss:0.35037	eval-mlogloss:0.29029
[80]	train-mlogloss:0.35014	eval-mlogloss:0.29024
[81]	train-mlogloss:0.35010	eval-mlogloss:0.29032
[82]	train-mlogloss:0.35001	eval-mlogloss:0.29004
[83]	train-mlogloss:0.34993	eval-mlogloss:0.28952
[84]	train-mlogloss:0.34981	eval-mlogloss:0.28966
[85]	train-mlogloss:0.34971	eval-mlogloss:0.28935
[86]	train-mlogloss:0.34970	eval-mlogloss:0.28942
[87]	train-mlogloss:0.34925	eval-mlogloss:0.28937
[88]	train-mlogloss:0.34905	eval-mlogloss:0.28912
[89]	train-mlogloss:0.34899	eval-mlogloss:0.28886
[90]	train-mlogloss:0.34911	eval-mlogloss:0.28928
[91]	train-mlogloss:0.34930	eval-mlogloss:0.28953
[92]	train-mlogloss:0.34927	eval-mlogloss:0.28942
[93]	train-mlogloss:0.34908	eval-mlogloss:0.28869
[94]	train-mlogloss:0.34919	eval-mlogloss:0.28902
[95]	train-mlogloss:0.34895	eval-mlogloss:0.28901
[96]	train-mlogloss:0.34829	eval-mlogloss:0.28838
[97]	train-mlogloss:0.34807	eval-mlogloss:0.28835
[98]	train-mlogloss:0.34778	eval-mlogloss:0.28905
[99]	train-mlogloss:0.34732	eval-mlogloss:0.28831
[100]	train-mlogloss:0.34724	eval-mlogloss:0.28792
[101]	train-mlogloss:0.34694	eval-mlogloss:0.28751
[102]	train-mlogloss:0.34691	eval-mlogloss:0.28746
[103]	train-mlogloss:0.34680	eval-mlogloss:0.28787
[104]	train-mlogloss:0.34596	eval-mlogloss:0.28764
[105]	train-mlogloss:0.34578	eval-mlogloss:0.28673
[106]	train-mlogloss:0.34550	eval-mlogloss:0.28712
[107]	train-mlogloss:0.34544	eval-mlogloss:0.28796
[108]	train-mlogloss:0.34500	eval-mlogloss:0.28742
[109]	train-mlogloss:0.34466	eval-mlogloss:0.28718
[110]	train-mlogloss:0.34469	eval-mlogloss:0.28735
[111]	train-mlogloss:0.34464	eval-mlogloss:0.28713
[112]	train-mlogloss:0.34460	eval-mlogloss:0.28657
[113]	train-mlogloss:0.34462	eval-mlogloss:0.28660
[114]	train-mlogloss:0.34446	eval-mlogloss:0.28708
[115]	train-mlogloss:0.34411	eval-mlogloss:0.28738
[116]	train-mlogloss:0.34394	eval-mlogloss:0.28749
[117]	train-mlogloss:0.34373	eval-mlogloss:0.28785
[118]	train-mlogloss:0.34367	eval-mlogloss:0.28764
[119]	train-mlogloss:0.34367	eval-mlogloss:0.28740
[120]	train-mlogloss:0.34357	eval-mlogloss:0.28761
[121]	train-mlogloss:0.34294	eval-mlogloss:0.28769
[122]	train-mlogloss:0.34292	eval-mlogloss:0.28785
[123]	train-mlogloss:0.34289	eval-mlogloss:0.28772
[124]	train-mlogloss:0.34250	eval-mlogloss:0.28670
[125]	train-mlogloss:0.34230	eval-mlogloss:0.28673
[126]	train-mlogloss:0.34192	eval-mlogloss:0.28546
[127]	train-mlogloss:0.34197	eval-mlogloss:0.28563
[128]	train-mlogloss:0.34167	eval-mlogloss:0.28413
[129]	train-mlogloss:0.34138	eval-mlogloss:0.28397
[130]	train-mlogloss:0.34157	eval-mlogloss:0.28456
[131]	train-mlogloss:0.34155	eval-mlogloss:0.28467
[132]	train-mlogloss:0.34137	eval-mlogloss:0.28396
[133]	train-mlogloss:0.34134	eval-mlogloss:0.28367
[134]	train-mlogloss:0.34131	eval-mlogloss:0.28338
[135]	train-mlogloss:0.34105	eval-mlogloss:0.28385
[136]	train-mlogloss:0.34110	eval-mlogloss:0.28408
[137]	train-mlogloss:0.34111	eval-mlogloss:0.28398
[138]	train-mlogloss:0.34077	eval-mlogloss:0.28311
[139]	train-mlogloss:0.34082	eval-mlogloss:0.28304
[140]	train-mlogloss:0.34076	eval-mlogloss:0.28315
[141]	train-mlogloss:0.34080	eval-mlogloss:0.28333
[142]	train-mlogloss:0.34092	eval-mlogloss:0.28403
[143]	train-mlogloss:0.34094	eval-mlogloss:0.28407
[144]	train-mlogloss:0.34072	eval-mlogloss:0.28383
[145]	train-mlogloss:0.34074	eval-mlogloss:0.28403
[146]	train-mlogloss:0.34067	eval-mlogloss:0.28356
[147]	train-mlogloss:0.34058	eval-mlogloss:0.28358
[148]	train-mlogloss:0.34062	eval-mlogloss:0.28397
[149]	train-mlogloss:0.34064	eval-mlogloss:0.28409
[150]	train-mlogloss:0.34063	eval-mlogloss:0.28374
[151]	train-mlogloss:0.34065	eval-mlogloss:0.28381
[152]	train-mlogloss:0.34070	eval-mlogloss:0.28378
[153]	train-mlogloss:0.34073	eval-mlogloss:0.28365
[154]	train-mlogloss:0.34087	eval-mlogloss:0.28306
[155]	train-mlogloss:0.34089	eval-mlogloss:0.28306
[156]	train-mlogloss:0.34100	eval-mlogloss:0.28326
[157]	train-mlogloss:0.34100	eval-mlogloss:0.28296
[158]	train-mlogloss:0.34086	eval-mlogloss:0.28295
[159]	train-mlogloss:0.34071	eval-mlogloss:0.28295
[160]	train-mlogloss:0.34072	eval-mlogloss:0.28263
[161]	train-mlogloss:0.34050	eval-mlogloss:0.28215
[162]	train-mlogloss:0.34052	eval-mlogloss:0.28194
[163]	train-mlogloss:0.34053	eval-mlogloss:0.28198
[164]	train-mlogloss:0.33987	eval-mlogloss:0.28186
[165]	train-mlogloss:0.33989	eval-mlogloss:0.28166
[166]	train-mlogloss:0.33980	eval-mlogloss:0.28197
[167]	train-mlogloss:0.33978	eval-mlogloss:0.28209
[168]	train-mlogloss:0.33973	eval-mlogloss:0.28257
[169]	train-mlogloss:0.33973	eval-mlogloss:0.28283
[170]	train-mlogloss:0.33974	eval-mlogloss:0.28296
[171]	train-mlogloss:0.33946	eval-mlogloss:0.28336
[172]	train-mlogloss:0.33933	eval-mlogloss:0.28271
[173]	train-mlogloss:0.33932	eval-mlogloss:0.28258
[174]	train-mlogloss:0.33938	eval-mlogloss:0.28351
[175]	train-mlogloss:0.33935	eval-mlogloss:0.28326
[176]	train-mlogloss:0.33932	eval-mlogloss:0.28288
[177]	train-mlogloss:0.33913	eval-mlogloss:0.28272
[178]	train-mlogloss:0.33929	eval-mlogloss:0.28321
[179]	train-mlogloss:0.33940	eval-mlogloss:0.28332
[180]	train-mlogloss:0.33928	eval-mlogloss:0.28206
[181]	train-mlogloss:0.33906	eval-mlogloss:0.28167
[182]	train-mlogloss:0.33904	eval-mlogloss:0.28118
[183]	train-mlogloss:0.33910	eval-mlogloss:0.28177
[184]	train-mlogloss:0.33888	eval-mlogloss:0.28168
[185]	train-mlogloss:0.33888	eval-mlogloss:0.28169
[186]	train-mlogloss:0.33870	eval-mlogloss:0.28052
[187]	train-mlogloss:0.33873	eval-mlogloss:0.28024
[188]	train-mlogloss:0.33869	eval-mlogloss:0.28083
[189]	train-mlogloss:0.33868	eval-mlogloss:0.28131
[190]	train-mlogloss:0.33808	eval-mlogloss:0.28106
[191]	train-mlogloss:0.33802	eval-mlogloss:0.28069
[192]	train-mlogloss:0.33800	eval-mlogloss:0.28082
[193]	train-mlogloss:0.33763	eval-mlogloss:0.28025
[194]	train-mlogloss:0.33744	eval-mlogloss:0.28055
[195]	train-mlogloss:0.33747	eval-mlogloss:0.28015
[196]	train-mlogloss:0.33736	eval-mlogloss:0.28054
[197]	train-mlogloss:0.33726	eval-mlogloss:0.28029
[198]	train-mlogloss:0.33726	eval-mlogloss:0.28006
[199]	train-mlogloss:0.33718	eval-mlogloss:0.27974
[200]	train-mlogloss:0.33719	eval-mlogloss:0.27975
[201]	train-mlogloss:0.33723	eval-mlogloss:0.27926
[202]	train-mlogloss:0.33719	eval-mlogloss:0.27935
[203]	train-mlogloss:0.33717	eval-mlogloss:0.27938
[204]	train-mlogloss:0.33713	eval-mlogloss:0.27946
[205]	train-mlogloss:0.33720	eval-mlogloss:0.27941
[206]	train-mlogloss:0.33709	eval-mlogloss:0.27948
[207]	train-mlogloss:0.33716	eval-mlogloss:0.27953
[208]	train-mlogloss:0.33707	eval-mlogloss:0.27952
[209]	train-mlogloss:0.33702	eval-mlogloss:0.27915
[210]	train-mlogloss:0.33702	eval-mlogloss:0.27916
[211]	train-mlogloss:0.33691	eval-mlogloss:0.27942
[212]	train-mlogloss:0.33693	eval-mlogloss:0.27961
[213]	train-mlogloss:0.33692	eval-mlogloss:0.27958
[214]	train-mlogloss:0.33705	eval-mlogloss:0.27895
[215]	train-mlogloss:0.33696	eval-mlogloss:0.27938
[216]	train-mlogloss:0.33703	eval-mlogloss:0.27900
[217]	train-mlogloss:0.33699	eval-mlogloss:0.27928
[218]	train-mlogloss:0.33704	eval-mlogloss:0.27985
[219]	train-mlogloss:0.33710	eval-mlogloss:0.27979
[220]	train-mlogloss:0.33706	eval-mlogloss:0.27990
[221]	train-mlogloss:0.33703	eval-mlogloss:0.28032
[222]	train-mlogloss:0.33702	eval-mlogloss:0.28021
[223]	train-mlogloss:0.33701	eval-mlogloss:0.28028
[224]	train-mlogloss:0.33688	eval-mlogloss:0.27972
[225]	train-mlogloss:0.33688	eval-mlogloss:0.27958
[226]	train-mlogloss:0.33690	eval-mlogloss:0.27888
[227]	train-mlogloss:0.33688	eval-mlogloss:0.27913
[228]	train-mlogloss:0.33687	eval-mlogloss:0.27931
[229]	train-mlogloss:0.33690	eval-mlogloss:0.27992
[230]	train-mlogloss:0.33693	eval-mlogloss:0.27999
[231]	train-mlogloss:0.33702	eval-mlogloss:0.28032
[232]	train-mlogloss:0.33691	eval-mlogloss:0.28004
[233]	train-mlogloss:0.33690	eval-mlogloss:0.27984
[234]	train-mlogloss:0.33697	eval-mlogloss:0.28057
[235]	train-mlogloss:0.33703	eval-mlogloss:0.28093
[236]	train-mlogloss:0.33701	eval-mlogloss:0.28087
[237]	train-mlogloss:0.33702	eval-mlogloss:0.28092
[238]	train-mlogloss:0.33709	eval-mlogloss:0.28121
[239]	train-mlogloss:0.33702	eval-mlogloss:0.28078
[240]	train-mlogloss:0.33703	eval-mlogloss:0.28074
[241]	train-mlogloss:0.33681	eval-mlogloss:0.28027
[242]	train-mlogloss:0.33689	eval-mlogloss:0.28076
[243]	train-mlogloss:0.33685	eval-mlogloss:0.28034
[244]	train-mlogloss:0.33681	eval-mlogloss:0.28034
[245]	train-mlogloss:0.33682	eval-mlogloss:0.28023
[246]	train-mlogloss:0.33680	eval-mlogloss:0.27928
[247]	train-mlogloss:0.33675	eval-mlogloss:0.27939
[248]	train-mlogloss:0.33675	eval-mlogloss:0.27942
[249]	train-mlogloss:0.33682	eval-mlogloss:0.27902
[250]	train-mlogloss:0.33682	eval-mlogloss:0.27884
[251]	train-mlogloss:0.33689	eval-mlogloss:0.27867
[252]	train-mlogloss:0.33689	eval-mlogloss:0.27782
[253]	train-mlogloss:0.33686	eval-mlogloss:0.27786
[254]	train-mlogloss:0.33668	eval-mlogloss:0.27834
[255]	train-mlogloss:0.33660	eval-mlogloss:0.27869
[256]	train-mlogloss:0.33660	eval-mlogloss:0.27868
[257]	train-mlogloss:0.33663	eval-mlogloss:0.27865
[258]	train-mlogloss:0.33675	eval-mlogloss:0.27826
[259]	train-mlogloss:0.33673	eval-mlogloss:0.27830
[260]	train-mlogloss:0.33686	eval-mlogloss:0.27803
[261]	train-mlogloss:0.33680	eval-mlogloss:0.27814
[262]	train-mlogloss:0.33668	eval-mlogloss:0.27845
[263]	train-mlogloss:0.33675	eval-mlogloss:0.27862
[264]	train-mlogloss:0.33614	eval-mlogloss:0.27797
[265]	train-mlogloss:0.33610	eval-mlogloss:0.27811
[266]	train-mlogloss:0.33598	eval-mlogloss:0.27849
[267]	train-mlogloss:0.33597	eval-mlogloss:0.27859
[268]	train-mlogloss:0.33599	eval-mlogloss:0.27850
[269]	train-mlogloss:0.33589	eval-mlogloss:0.27870
[270]	train-mlogloss:0.33590	eval-mlogloss:0.27840
[271]	train-mlogloss:0.33590	eval-mlogloss:0.27865
[272]	train-mlogloss:0.33590	eval-mlogloss:0.27865
[273]	train-mlogloss:0.33587	eval-mlogloss:0.27878
[274]	train-mlogloss:0.33587	eval-mlogloss:0.27907
[275]	train-mlogloss:0.33587	eval-mlogloss:0.27916
[276]	train-mlogloss:0.33588	eval-mlogloss:0.27869
[277]	train-mlogloss:0.33586	eval-mlogloss:0.27894
[278]	train-mlogloss:0.33577	eval-mlogloss:0.27855
[279]	train-mlogloss:0.33577	eval-mlogloss:0.27833
[280]	train-mlogloss:0.33579	eval-mlogloss:0.27791
[281]	train-mlogloss:0.33577	eval-mlogloss:0.27819
[282]	train-mlogloss:0.33600	eval-mlogloss:0.27809

[I 2026-06-30 13:48:13,222] Trial 4 finished with value: 0.9666666666666667 and parameters: {'lambda': 5.575799415987621e-07, 'alpha': 0.002354442572012447, 'eta': 0.12727117916754271, 'gamma': 8.495182200361812e-08, 'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.542848067933777, 'colsample_bytree': 0.8787345576849964}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.00522	eval-mlogloss:0.99723
[1]	train-mlogloss:0.87743	eval-mlogloss:0.86333

[I 2026-06-30 13:48:13,254] Trial 5 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.89125	eval-mlogloss:0.88450
[1]	train-mlogloss:0.69502	eval-mlogloss:0.66813

[I 2026-06-30 13:48:13,261] Trial 6 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.78956	eval-mlogloss:0.76344
[1]	train-mlogloss:0.59370	eval-mlogloss:0.56024

[I 2026-06-30 13:48:13,268] Trial 7 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.87487	eval-mlogloss:0.86357
[1]	train-mlogloss:0.65201	eval-mlogloss:0.62398

[I 2026-06-30 13:48:13,276] Trial 8 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.87014	eval-mlogloss:0.88197
[1]	train-mlogloss:0.66261	eval-mlogloss:0.64429

[I 2026-06-30 13:48:13,282] Trial 9 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.09021	eval-mlogloss:1.09291
[1]	train-mlogloss:1.07065	eval-mlogloss:1.07255
[2]	train-mlogloss:1.05151	eval-mlogloss:1.05244
[3]	train-mlogloss:1.03717	eval-mlogloss:1.03693
[4]	train-mlogloss:1.02184	eval-mlogloss:1.02101
[5]	train-mlogloss:1.00396	eval-mlogloss:1.00222
[6]	train-mlogloss:0.99041	eval-mlogloss:0.98862
[7]	train-mlogloss:0.97991	eval-mlogloss:0.97873
[8]	train-mlogloss:0.96311	eval-mlogloss:0.96105
[9]	train-mlogloss:0.95038	eval-mlogloss:0.94834
[10]	train-mlogloss:0.93422	eval-mlogloss:0.93171
[11]	train-mlogloss:0.92034	eval-mlogloss:0.91739
[12]	train-mlogloss:0.91413	eval-mlogloss:0.91103
[13]	train-mlogloss:0.89899	eval-mlogloss:0.89483
[14]	train-mlogloss:0.89324	eval-mlogloss:0.88995
[15]	train-mlogloss:0.88441	eval-mlogloss:0.88132
[16]	train-mlogloss:0.87489	eval-mlogloss:0.87170
[17]	train-mlogloss:0.86387	eval-mlogloss:0.86069
[18]	train-mlogloss:0.85534	eval-mlogloss:0.85258
[19]	train-mlogloss:0.84696	eval-mlogloss:0.84460
[20]	train-mlogloss:0.83329	eval-mlogloss:0.83013
[21]	train-mlogloss:0.82368	eval-mlogloss:0.82066
[22]	train-mlogloss:0.81512	eval-mlogloss:0.81206
[23]	train-mlogloss:0.80223	eval-mlogloss:0.79846
[24]	train-mlogloss:0.79472	eval-mlogloss:0.79049
[25]	train-mlogloss:0.78526	eval-mlogloss:0.78008
[26]	train-mlogloss:0.77501	eval-mlogloss:0.76954
[27]	train-mlogloss:0.77183	eval-mlogloss:0.76697
[28]	train-mlogloss:0.76752	eval-mlogloss:0.76340
[29]	train-mlogloss:0.75804	eval-mlogloss:0.75314
[30]	train-mlogloss:0.74915	eval-mlogloss:0.74391
[31]	train-mlogloss:0.74601	eval-mlogloss:0.74170
[32]	train-mlogloss:0.74009	eval-mlogloss:0.73627
[33]	train-mlogloss:0.73477	eval-mlogloss:0.73098
[34]	train-mlogloss:0.72485	eval-mlogloss:0.72061
[35]	train-mlogloss:0.71884	eval-mlogloss:0.71411
[36]	train-mlogloss:0.71381	eval-mlogloss:0.70934
[37]	train-mlogloss:0.70626	eval-mlogloss:0.70221
[38]	train-mlogloss:0.69781	eval-mlogloss:0.69336
[39]	train-mlogloss:0.69146	eval-mlogloss:0.68718
[40]	train-mlogloss:0.68791	eval-mlogloss:0.68394
[41]	train-mlogloss:0.68042	eval-mlogloss:0.67548
[42]	train-mlogloss:0.67783	eval-mlogloss:0.67382
[43]	train-mlogloss:0.67074	eval-mlogloss:0.66631
[44]	train-mlogloss:0.66326	eval-mlogloss:0.65850
[45]	train-mlogloss:0.65901	eval-mlogloss:0.65371
[46]	train-mlogloss:0.65181	eval-mlogloss:0.64618
[47]	train-mlogloss:0.64650	eval-mlogloss:0.64127
[48]	train-mlogloss:0.63897	eval-mlogloss:0.63351
[49]	train-mlogloss:0.63157	eval-mlogloss:0.62589
[50]	train-mlogloss:0.62438	eval-mlogloss:0.61811
[51]	train-mlogloss:0.61996	eval-mlogloss:0.61401
[52]	train-mlogloss:0.61570	eval-mlogloss:0.61040
[53]	train-mlogloss:0.60699	eval-mlogloss:0.60071
[54]	train-mlogloss:0.60277	eval-mlogloss:0.59664
[55]	train-mlogloss:0.59432	eval-mlogloss:0.58790
[56]	train-mlogloss:0.58773	eval-mlogloss:0.58096
[57]	train-mlogloss:0.57956	eval-mlogloss:0.57190
[58]	train-mlogloss:0.57524	eval-mlogloss:0.56807
[59]	train-mlogloss:0.57269	eval-mlogloss:0.56554
[60]	train-mlogloss:0.56693	eval-mlogloss:0.55906
[61]	train-mlogloss:0.56207	eval-mlogloss:0.55386
[62]	train-mlogloss:0.55438	eval-mlogloss:0.54589
[63]	train-mlogloss:0.55036	eval-mlogloss:0.54219
[64]	train-mlogloss:0.54791	eval-mlogloss:0.54010
[65]	train-mlogloss:0.54383	eval-mlogloss:0.53600
[66]	train-mlogloss:0.53809	eval-mlogloss:0.53029
[67]	train-mlogloss:0.53357	eval-mlogloss:0.52569
[68]	train-mlogloss:0.53130	eval-mlogloss:0.52323
[69]	train-mlogloss:0.52424	eval-mlogloss:0.51564
[70]	train-mlogloss:0.52011	eval-mlogloss:0.51120
[71]	train-mlogloss:0.51326	eval-mlogloss:0.50383
[72]	train-mlogloss:0.50791	eval-mlogloss:0.49815
[73]	train-mlogloss:0.50398	eval-mlogloss:0.49392
[74]	train-mlogloss:0.49934	eval-mlogloss:0.48909
[75]	train-mlogloss:0.49359	eval-mlogloss:0.48266
[76]	train-mlogloss:0.49023	eval-mlogloss:0.47954
[77]	train-mlogloss:0.48743	eval-mlogloss:0.47713
[78]	train-mlogloss:0.48440	eval-mlogloss:0.47417
[79]	train-mlogloss:0.48166	eval-mlogloss:0.47195
[80]	train-mlogloss:0.47853	eval-mlogloss:0.46875
[81]	train-mlogloss:0.47378	eval-mlogloss:0.46398
[82]	train-mlogloss:0.47090	eval-mlogloss:0.46115
[83]	train-mlogloss:0.46683	eval-mlogloss:0.45644
[84]	train-mlogloss:0.46342	eval-mlogloss:0.45277
[85]	train-mlogloss:0.45909	eval-mlogloss:0.44816
[86]	train-mlogloss:0.45456	eval-mlogloss:0.44304
[87]	train-mlogloss:0.45014	eval-mlogloss:0.43827
[88]	train-mlogloss:0.44675	eval-mlogloss:0.43431
[89]	train-mlogloss:0.44232	eval-mlogloss:0.42967
[90]	train-mlogloss:0.43836	eval-mlogloss:0.42520
[91]	train-mlogloss:0.43527	eval-mlogloss:0.42215
[92]	train-mlogloss:0.43056	eval-mlogloss:0.41712
[93]	train-mlogloss:0.42895	eval-mlogloss:0.41587
[94]	train-mlogloss:0.42368	eval-mlogloss:0.40978
[95]	train-mlogloss:0.41919	eval-mlogloss:0.40451
[96]	train-mlogloss:0.41412	eval-mlogloss:0.39891
[97]	train-mlogloss:0.41156	eval-mlogloss:0.39649
[98]	train-mlogloss:0.40859	eval-mlogloss:0.39298
[99]	train-mlogloss:0.40762	eval-mlogloss:0.39246
[100]	train-mlogloss:0.40419	eval-mlogloss:0.38913
[101]	train-mlogloss:0.40133	eval-mlogloss:0.38574
[102]	train-mlogloss:0.39903	eval-mlogloss:0.38362
[103]	train-mlogloss:0.39426	eval-mlogloss:0.37825
[104]	train-mlogloss:0.39163	eval-mlogloss:0.37573
[105]	train-mlogloss:0.38920	eval-mlogloss:0.37340
[106]	train-mlogloss:0.38620	eval-mlogloss:0.37015
[107]	train-mlogloss:0.38170	eval-mlogloss:0.36492
[108]	train-mlogloss:0.37938	eval-mlogloss:0.36246
[109]	train-mlogloss:0.37501	eval-mlogloss:0.35737
[110]	train-mlogloss:0.37246	eval-mlogloss:0.35430
[111]	train-mlogloss:0.36910	eval-mlogloss:0.35055
[112]	train-mlogloss:0.36673	eval-mlogloss:0.34819
[113]	train-mlogloss:0.36258	eval-mlogloss:0.34337
[114]	train-mlogloss:0.36047	eval-mlogloss:0.34141
[115]	train-mlogloss:0.35764	eval-mlogloss:0.33840
[116]	train-mlogloss:0.35361	eval-mlogloss:0.33397
[117]	train-mlogloss:0.35055	eval-mlogloss:0.33054
[118]	train-mlogloss:0.34772	eval-mlogloss:0.32761
[119]	train-mlogloss:0.34558	eval-mlogloss:0.32525
[120]	train-mlogloss:0.34176	eval-mlogloss:0.32097
[121]	train-mlogloss:0.33881	eval-mlogloss:0.31790
[122]	train-mlogloss:0.33513	eval-mlogloss:0.31356
[123]	train-mlogloss:0.33194	eval-mlogloss:0.31002
[124]	train-mlogloss:0.32946	eval-mlogloss:0.30738
[125]	train-mlogloss:0.32693	eval-mlogloss:0.30447
[126]	train-mlogloss:0.32507	eval-mlogloss:0.30244
[127]	train-mlogloss:0.32334	eval-mlogloss:0.30063
[128]	train-mlogloss:0.32093	eval-mlogloss:0.29792
[129]	train-mlogloss:0.31933	eval-mlogloss:0.29607
[130]	train-mlogloss:0.31882	eval-mlogloss:0.29577
[131]	train-mlogloss:0.31549	eval-mlogloss:0.29182
[132]	train-mlogloss:0.31297	eval-mlogloss:0.28898
[133]	train-mlogloss:0.31093	eval-mlogloss:0.28663
[134]	train-mlogloss:0.30941	eval-mlogloss:0.28523
[135]	train-mlogloss:0.30699	eval-mlogloss:0.28231
[136]	train-mlogloss:0.30504	eval-mlogloss:0.28007
[137]	train-mlogloss:0.30179	eval-mlogloss:0.27664
[138]	train-mlogloss:0.29965	eval-mlogloss:0.27425
[139]	train-mlogloss:0.29819	eval-mlogloss:0.27295
[140]	train-mlogloss:0.29590	eval-mlogloss:0.27034
[141]	train-mlogloss:0.29370	eval-mlogloss:0.26804
[142]	train-mlogloss:0.29146	eval-mlogloss:0.26560
[143]	train-mlogloss:0.28850	eval-mlogloss:0.26254
[144]	train-mlogloss:0.28615	eval-mlogloss:0.25974
[145]	train-mlogloss:0.28463	eval-mlogloss:0.25782
[146]	train-mlogloss:0.28281	eval-mlogloss:0.25561
[147]	train-mlogloss:0.28115	eval-mlogloss:0.25370
[148]	train-mlogloss:0.27935	eval-mlogloss:0.25150
[149]	train-mlogloss:0.27869	eval-mlogloss:0.25080
[150]	train-mlogloss:0.27622	eval-mlogloss:0.24795
[151]	train-mlogloss:0.27384	eval-mlogloss:0.24495
[152]	train-mlogloss:0.27261	eval-mlogloss:0.24367
[153]	train-mlogloss:0.27086	eval-mlogloss:0.24189
[154]	train-mlogloss:0.26831	eval-mlogloss:0.23922
[155]	train-mlogloss:0.26666	eval-mlogloss:0.23721
[156]	train-mlogloss:0.26504	eval-mlogloss:0.23521
[157]	train-mlogloss:0.26386	eval-mlogloss:0.23402
[158]	train-mlogloss:0.26195	eval-mlogloss:0.23177
[159]	train-mlogloss:0.26079	eval-mlogloss:0.23036
[160]	train-mlogloss:0.25884	eval-mlogloss:0.22812
[161]	train-mlogloss:0.25647	eval-mlogloss:0.22550
[162]	train-mlogloss:0.25555	eval-mlogloss:0.22437
[163]	train-mlogloss:0.25467	eval-mlogloss:0.22325
[164]	train-mlogloss:0.25420	eval-mlogloss:0.22286
[165]	train-mlogloss:0.25315	eval-mlogloss:0.22167
[166]	train-mlogloss:0.25098	eval-mlogloss:0.21912
[167]	train-mlogloss:0.24887	eval-mlogloss:0.21667
[168]	train-mlogloss:0.24728	eval-mlogloss:0.21488
[169]	train-mlogloss:0.24634	eval-mlogloss:0.21409
[170]	train-mlogloss:0.24597	eval-mlogloss:0.21401
[171]	train-mlogloss:0.24455	eval-mlogloss:0.21261
[172]	train-mlogloss:0.24401	eval-mlogloss:0.21229
[173]	train-mlogloss:0.24330	eval-mlogloss:0.21152
[174]	train-mlogloss:0.24215	eval-mlogloss:0.21021
[175]	train-mlogloss:0.24108	eval-mlogloss:0.20916
[176]	train-mlogloss:0.23946	eval-mlogloss:0.20724
[177]	train-mlogloss:0.23891	eval-mlogloss:0.20667
[178]	train-mlogloss:0.23738	eval-mlogloss:0.20514
[179]	train-mlogloss:0.23665	eval-mlogloss:0.20433
[180]	train-mlogloss:0.23530	eval-mlogloss:0.20279
[181]	train-mlogloss:0.23380	eval-mlogloss:0.20132
[182]	train-mlogloss:0.23291	eval-mlogloss:0.20045
[183]	train-mlogloss:0.23260	eval-mlogloss:0.20028
[184]	train-mlogloss:0.23119	eval-mlogloss:0.19890
[185]	train-mlogloss:0.22981	eval-mlogloss:0.19750
[186]	train-mlogloss:0.22838	eval-mlogloss:0.19608
[187]	train-mlogloss:0.22711	eval-mlogloss:0.19462
[188]	train-mlogloss:0.22567	eval-mlogloss:0.19286
[189]	train-mlogloss:0.22384	eval-mlogloss:0.19090
[190]	train-mlogloss:0.22313	eval-mlogloss:0.19012
[191]	train-mlogloss:0.22199	eval-mlogloss:0.18864
[192]	train-mlogloss:0.22102	eval-mlogloss:0.18767
[193]	train-mlogloss:0.22004	eval-mlogloss:0.18645
[194]	train-mlogloss:0.21883	eval-mlogloss:0.18506
[195]	train-mlogloss:0.21721	eval-mlogloss:0.18331
[196]	train-mlogloss:0.21616	eval-mlogloss:0.18230
[197]	train-mlogloss:0.21458	eval-mlogloss:0.18063
[198]	train-mlogloss:0.21385	eval-mlogloss:0.17985
[199]	train-mlogloss:0.21312	eval-mlogloss:0.17902
[200]	train-mlogloss:0.21209	eval-mlogloss:0.17792
[201]	train-mlogloss:0.21143	eval-mlogloss:0.17728
[202]	train-mlogloss:0.21086	eval-mlogloss:0.17686
[203]	train-mlogloss:0.20980	eval-mlogloss:0.17578
[204]	train-mlogloss:0.20913	eval-mlogloss:0.17515
[205]	train-mlogloss:0.20856	eval-mlogloss:0.17448
[206]	train-mlogloss:0.20770	eval-mlogloss:0.17359
[207]	train-mlogloss:0.20686	eval-mlogloss:0.17256
[208]	train-mlogloss:0.20577	eval-mlogloss:0.17146
[209]	train-mlogloss:0.20439	eval-mlogloss:0.16966
[210]	train-mlogloss:0.20403	eval-mlogloss:0.16947
[211]	train-mlogloss:0.20343	eval-mlogloss:0.16901
[212]	train-mlogloss:0.20238	eval-mlogloss:0.16791
[213]	train-mlogloss:0.20135	eval-mlogloss:0.16666
[214]	train-mlogloss:0.20001	eval-mlogloss:0.16506
[215]	train-mlogloss:0.19872	eval-mlogloss:0.16343
[216]	train-mlogloss:0.19823	eval-mlogloss:0.16291
[217]	train-mlogloss:0.19700	eval-mlogloss:0.16130
[218]	train-mlogloss:0.19667	eval-mlogloss:0.16109
[219]	train-mlogloss:0.19544	eval-mlogloss:0.15971
[220]	train-mlogloss:0.19486	eval-mlogloss:0.15913
[221]	train-mlogloss:0.19428	eval-mlogloss:0.15857
[222]	train-mlogloss:0.19372	eval-mlogloss:0.15798
[223]	train-mlogloss:0.19316	eval-mlogloss:0.15741
[224]	train-mlogloss:0.19235	eval-mlogloss:0.15647
[225]	train-mlogloss:0.19203	eval-mlogloss:0.15619
[226]	train-mlogloss:0.19126	eval-mlogloss:0.15525
[227]	train-mlogloss:0.19083	eval-mlogloss:0.15490
[228]	train-mlogloss:0.19028	eval-mlogloss:0.15432
[229]	train-mlogloss:0.18962	eval-mlogloss:0.15358
[230]	train-mlogloss:0.18944	eval-mlogloss:0.15339
[231]	train-mlogloss:0.18874	eval-mlogloss:0.15252
[232]	train-mlogloss:0.18856	eval-mlogloss:0.15252
[233]	train-mlogloss:0.18790	eval-mlogloss:0.15166
[234]	train-mlogloss:0.18690	eval-mlogloss:0.15024
[235]	train-mlogloss:0.18602	eval-mlogloss:0.14898
[236]	train-mlogloss:0.18548	eval-mlogloss:0.14841
[237]	train-mlogloss:0.18485	eval-mlogloss:0.14764
[238]	train-mlogloss:0.18420	eval-mlogloss:0.14677
[239]	train-mlogloss:0.18358	eval-mlogloss:0.14608
[240]	train-mlogloss:0.18297	eval-mlogloss:0.14514
[241]	train-mlogloss:0.18257	eval-mlogloss:0.14465
[242]	train-mlogloss:0.18200	eval-mlogloss:0.14391
[243]	train-mlogloss:0.18162	eval-mlogloss:0.14347
[244]	train-mlogloss:0.18121	eval-mlogloss:0.14315
[245]	train-mlogloss:0.18082	eval-mlogloss:0.14258
[246]	train-mlogloss:0.18055	eval-mlogloss:0.14215
[247]	train-mlogloss:0.18047	eval-mlogloss:0.14202
[248]	train-mlogloss:0.18038	eval-mlogloss:0.14208
[249]	train-mlogloss:0.17980	eval-mlogloss:0.14118
[250]	train-mlogloss:0.17942	eval-mlogloss:0.14059
[251]	train-mlogloss:0.17903	eval-mlogloss:0.14011
[252]	train-mlogloss:0.17857	eval-mlogloss:0.13964
[253]	train-mlogloss:0.17820	eval-mlogloss:0.13910
[254]	train-mlogloss:0.17798	eval-mlogloss:0.13890
[255]	train-mlogloss:0.17772	eval-mlogloss:0.13864
[256]	train-mlogloss:0.17717	eval-mlogloss:0.13799
[257]	train-mlogloss:0.17666	eval-mlogloss:0.13731
[258]	train-mlogloss:0.17630	eval-mlogloss:0.13679
[259]	train-mlogloss:0.17623	eval-mlogloss:0.13689
[260]	train-mlogloss:0.17617	eval-mlogloss:0.13698
[261]	train-mlogloss:0.17595	eval-mlogloss:0.13662
[262]	train-mlogloss:0.17539	eval-mlogloss:0.13597
[263]	train-mlogloss:0.17483	eval-mlogloss:0.13517
[264]	train-mlogloss:0.17474	eval-mlogloss:0.13518
[265]	train-mlogloss:0.17467	eval-mlogloss:0.13510
[266]	train-mlogloss:0.17432	eval-mlogloss:0.13473
[267]	train-mlogloss:0.17425	eval-mlogloss:0.13465
[268]	train-mlogloss:0.17390	eval-mlogloss:0.13410
[269]	train-mlogloss:0.17344	eval-mlogloss:0.13336
[270]	train-mlogloss:0.17308	eval-mlogloss:0.13296
[271]	train-mlogloss:0.17281	eval-mlogloss:0.13278
[272]	train-mlogloss:0.17230	eval-mlogloss:0.13205
[273]	train-mlogloss:0.17223	eval-mlogloss:0.13195
[274]	train-mlogloss:0.17215	eval-mlogloss:0.13183
[275]	train-mlogloss:0.17169	eval-mlogloss:0.13122
[276]	train-mlogloss:0.17151	eval-mlogloss:0.13092
[277]	train-mlogloss:0.17113	eval-mlogloss:0.13046
[278]	train-mlogloss:0.17094	eval-mlogloss:0.13016
[279]	train-mlogloss:0.17057	eval-mlogloss:0.12960
[280]	train-mlogloss:0.17006	eval-mlogloss:0.12887
[281]	train-mlogloss:0.16976	eval-mlogloss:0.12854
[282]	train-mlogloss:0.16928	eval-mlogloss:0.12797
[283]	train-mlogloss:0.16923	eval-mlogloss:0.12790
[284]	train-mlogloss:0.16886	eval-mlogloss:0.12733
[285]	train-mlogloss:0.16879	eval-mlogloss:0.12742
[286]	train-mlogloss:0.16832	eval-mlogloss:0.12686
[287]	train-mlogloss:0.16796	eval-mlogloss:0.12631
[288]	train-mlogloss:0.16790	eval-mlogloss:0.12625
[289]	train-mlogloss:0.16771	eval-mlogloss:0.12598
[290]	train-mlogloss:0.16739	eval-mlogloss:0.12561
[291]	train-mlogloss:0.16711	eval-mlogloss:0.12526
[292]	train-mlogloss:0.16703	eval-mlogloss:0.12530
[293]	train-mlogloss:0.16679	eval-mlogloss:0.12515
[294]	train-mlogloss:0.16635	eval-mlogloss:0.12462
[295]	train-mlogloss:0.16604	eval-mlogloss:0.12415
[296]	train-mlogloss:0.16597	eval-mlogloss:0.12407
[297]	train-mlogloss:0.16554	eval-mlogloss:0.12345
[298]	train-mlogloss:0.16544	eval-mlogloss:0.12331
[299]	train-mlogloss:0.16507	eval-mlogloss:0.12272

[I 2026-06-30 13:48:14,209] Trial 10 finished with value: 1.0 and parameters: {'lambda': 0.8354237849369901, 'alpha': 1.8052690898203055e-08, 'eta': 0.015839975133589285, 'gamma': 0.0008635852495328765, 'max_depth': 3, 'min_child_weight': 6, 'subsample': 0.9889668931880571, 'colsample_bytree': 0.4083091793730088}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.94297	eval-mlogloss:0.95189
[1]	train-mlogloss:0.75845	eval-mlogloss:0.75628

[I 2026-06-30 13:48:14,244] Trial 11 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.92049	eval-mlogloss:0.92642
[1]	train-mlogloss:0.73166	eval-mlogloss:0.72650

[I 2026-06-30 13:48:14,279] Trial 12 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.94237	eval-mlogloss:0.94009
[1]	train-mlogloss:0.75620	eval-mlogloss:0.74027

[I 2026-06-30 13:48:14,310] Trial 13 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03666	eval-mlogloss:1.03409
[1]	train-mlogloss:0.99593	eval-mlogloss:0.98796
[2]	train-mlogloss:0.94297	eval-mlogloss:0.93143
[3]	train-mlogloss:0.89168	eval-mlogloss:0.87631
[4]	train-mlogloss:0.84835	eval-mlogloss:0.83240
[5]	train-mlogloss:0.80441	eval-mlogloss:0.78578
[6]	train-mlogloss:0.76362	eval-mlogloss:0.74204
[7]	train-mlogloss:0.73159	eval-mlogloss:0.71224

[I 2026-06-30 13:48:14,355] Trial 14 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.02412	eval-mlogloss:1.02118
[1]	train-mlogloss:0.84880	eval-mlogloss:0.83676

[I 2026-06-30 13:48:14,385] Trial 15 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.82410	eval-mlogloss:0.80362
[1]	train-mlogloss:0.64361	eval-mlogloss:0.60882

[I 2026-06-30 13:48:14,407] Trial 16 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.01607	eval-mlogloss:1.01489
[1]	train-mlogloss:0.83820	eval-mlogloss:0.82874

[I 2026-06-30 13:48:14,431] Trial 17 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.83583	eval-mlogloss:0.82072
[1]	train-mlogloss:0.60379	eval-mlogloss:0.58535

[I 2026-06-30 13:48:14,452] Trial 18 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.00462	eval-mlogloss:0.99858
[1]	train-mlogloss:0.92314	eval-mlogloss:0.91547
[2]	train-mlogloss:0.84981	eval-mlogloss:0.83869
[3]	train-mlogloss:0.78435	eval-mlogloss:0.77021
[4]	train-mlogloss:0.72645	eval-mlogloss:0.71107
[5]	train-mlogloss:0.67442	eval-mlogloss:0.65687
[6]	train-mlogloss:0.62784	eval-mlogloss:0.60734
[7]	train-mlogloss:0.58592	eval-mlogloss:0.56251

[I 2026-06-30 13:48:14,490] Trial 19 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.83376	eval-mlogloss:0.81093
[1]	train-mlogloss:0.65187	eval-mlogloss:0.61792

[I 2026-06-30 13:48:14,512] Trial 20 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.90997	eval-mlogloss:0.89889
[1]	train-mlogloss:0.80522	eval-mlogloss:0.77772

[I 2026-06-30 13:48:14,538] Trial 21 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.88776	eval-mlogloss:0.87535
[1]	train-mlogloss:0.73208	eval-mlogloss:0.70592

[I 2026-06-30 13:48:14,561] Trial 22 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.98323	eval-mlogloss:0.97955
[1]	train-mlogloss:0.88885	eval-mlogloss:0.86685
[2]	train-mlogloss:0.81474	eval-mlogloss:0.79412
[3]	train-mlogloss:0.70699	eval-mlogloss:0.68027
[4]	train-mlogloss:0.64813	eval-mlogloss:0.61647
[5]	train-mlogloss:0.59062	eval-mlogloss:0.55511
[6]	train-mlogloss:0.54328	eval-mlogloss:0.50573
[7]	train-mlogloss:0.52338	eval-mlogloss:0.48537

[I 2026-06-30 13:48:14,600] Trial 23 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.03218	eval-mlogloss:1.03708
[1]	train-mlogloss:0.95685	eval-mlogloss:0.95043
[2]	train-mlogloss:0.86627	eval-mlogloss:0.85771
[3]	train-mlogloss:0.78226	eval-mlogloss:0.76855
[4]	train-mlogloss:0.71426	eval-mlogloss:0.69770
[5]	train-mlogloss:0.65296	eval-mlogloss:0.62946
[6]	train-mlogloss:0.61059	eval-mlogloss:0.58361
[7]	train-mlogloss:0.56547	eval-mlogloss:0.54081

[I 2026-06-30 13:48:14,646] Trial 24 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.98392	eval-mlogloss:0.98032
[1]	train-mlogloss:0.90460	eval-mlogloss:0.88203
[2]	train-mlogloss:0.82609	eval-mlogloss:0.80421
[3]	train-mlogloss:0.72368	eval-mlogloss:0.70240
[4]	train-mlogloss:0.66683	eval-mlogloss:0.64562
[5]	train-mlogloss:0.59930	eval-mlogloss:0.57402
[6]	train-mlogloss:0.55174	eval-mlogloss:0.52644
[7]	train-mlogloss:0.52908	eval-mlogloss:0.50315

[I 2026-06-30 13:48:14,687] Trial 25 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.98720	eval-mlogloss:0.98601
[1]	train-mlogloss:0.75971	eval-mlogloss:0.74511

[I 2026-06-30 13:48:14,717] Trial 26 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.97591	eval-mlogloss:0.97776
[1]	train-mlogloss:0.83778	eval-mlogloss:0.82089

[I 2026-06-30 13:48:14,745] Trial 27 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.91565	eval-mlogloss:0.90426
[1]	train-mlogloss:0.77572	eval-mlogloss:0.75433

[I 2026-06-30 13:48:14,770] Trial 28 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.99609	eval-mlogloss:0.99506
[1]	train-mlogloss:0.88310	eval-mlogloss:0.87950

[I 2026-06-30 13:48:14,808] Trial 29 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.88080	eval-mlogloss:0.86339
[1]	train-mlogloss:0.72351	eval-mlogloss:0.69806

[I 2026-06-30 13:48:14,830] Trial 30 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.07735	eval-mlogloss:1.08099
[1]	train-mlogloss:1.02831	eval-mlogloss:1.02985
[2]	train-mlogloss:0.98236	eval-mlogloss:0.98148
[3]	train-mlogloss:0.94927	eval-mlogloss:0.94564
[4]	train-mlogloss:0.91490	eval-mlogloss:0.90980
[5]	train-mlogloss:0.87611	eval-mlogloss:0.86893
[6]	train-mlogloss:0.84784	eval-mlogloss:0.84065
[7]	train-mlogloss:0.82630	eval-mlogloss:0.82022
[8]	train-mlogloss:0.79274	eval-mlogloss:0.78471
[9]	train-mlogloss:0.76831	eval-mlogloss:0.76028
[10]	train-mlogloss:0.73783	eval-mlogloss:0.72878
[11]	train-mlogloss:0.71255	eval-mlogloss:0.70295
[12]	train-mlogloss:0.70204	eval-mlogloss:0.69206
[13]	train-mlogloss:0.67533	eval-mlogloss:0.66309
[14]	train-mlogloss:0.66589	eval-mlogloss:0.65527
[15]	train-mlogloss:0.65103	eval-mlogloss:0.64132
[16]	train-mlogloss:0.63555	eval-mlogloss:0.62563
[17]	train-mlogloss:0.61796	eval-mlogloss:0.60801
[18]	train-mlogloss:0.60467	eval-mlogloss:0.59549
[19]	train-mlogloss:0.59185	eval-mlogloss:0.58339
[20]	train-mlogloss:0.57091	eval-mlogloss:0.56114
[21]	train-mlogloss:0.55644	eval-mlogloss:0.54650
[22]	train-mlogloss:0.54419	eval-mlogloss:0.53408
[23]	train-mlogloss:0.52530	eval-mlogloss:0.51367
[24]	train-mlogloss:0.51558	eval-mlogloss:0.50303
[25]	train-mlogloss:0.50288	eval-mlogloss:0.48877
[26]	train-mlogloss:0.48940	eval-mlogloss:0.47482
[27]	train-mlogloss:0.48567	eval-mlogloss:0.47219
[28]	train-mlogloss:0.48053	eval-mlogloss:0.46815
[29]	train-mlogloss:0.46770	eval-mlogloss:0.45361
[30]	train-mlogloss:0.45649	eval-mlogloss:0.44183
[31]	train-mlogloss:0.45299	eval-mlogloss:0.43997

[I 2026-06-30 13:48:14,929] Trial 31 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:1.02618	eval-mlogloss:1.02606
[1]	train-mlogloss:0.92884	eval-mlogloss:0.92454
[2]	train-mlogloss:0.84345	eval-mlogloss:0.83458
[3]	train-mlogloss:0.76821	eval-mlogloss:0.75645
[4]	train-mlogloss:0.70211	eval-mlogloss:0.68735
[5]	train-mlogloss:0.64291	eval-mlogloss:0.62316
[6]	train-mlogloss:0.59248	eval-mlogloss:0.57141
[7]	train-mlogloss:0.54747	eval-mlogloss:0.52499

[I 2026-06-30 13:48:14,978] Trial 32 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.08116	eval-mlogloss:1.08580
[1]	train-mlogloss:1.04216	eval-mlogloss:1.04468
[2]	train-mlogloss:1.00478	eval-mlogloss:1.00529
[3]	train-mlogloss:0.97719	eval-mlogloss:0.97548
[4]	train-mlogloss:0.94833	eval-mlogloss:0.94638
[5]	train-mlogloss:0.91591	eval-mlogloss:0.91181
[6]	train-mlogloss:0.89172	eval-mlogloss:0.88753
[7]	train-mlogloss:0.87310	eval-mlogloss:0.86957
[8]	train-mlogloss:0.84436	eval-mlogloss:0.83922
[9]	train-mlogloss:0.82300	eval-mlogloss:0.81832
[10]	train-mlogloss:0.79630	eval-mlogloss:0.79048
[11]	train-mlogloss:0.77337	eval-mlogloss:0.76674
[12]	train-mlogloss:0.76308	eval-mlogloss:0.75756
[13]	train-mlogloss:0.73926	eval-mlogloss:0.73157
[14]	train-mlogloss:0.73069	eval-mlogloss:0.72395
[15]	train-mlogloss:0.71703	eval-mlogloss:0.71017
[16]	train-mlogloss:0.70277	eval-mlogloss:0.69596
[17]	train-mlogloss:0.68644	eval-mlogloss:0.68002
[18]	train-mlogloss:0.67401	eval-mlogloss:0.66789
[19]	train-mlogloss:0.66188	eval-mlogloss:0.65582
[20]	train-mlogloss:0.64219	eval-mlogloss:0.63444
[21]	train-mlogloss:0.62864	eval-mlogloss:0.62084
[22]	train-mlogloss:0.61683	eval-mlogloss:0.60867
[23]	train-mlogloss:0.59886	eval-mlogloss:0.58923
[24]	train-mlogloss:0.58863	eval-mlogloss:0.57927
[25]	train-mlogloss:0.57591	eval-mlogloss:0.56547
[26]	train-mlogloss:0.56242	eval-mlogloss:0.55255
[27]	train-mlogloss:0.55844	eval-mlogloss:0.54981
[28]	train-mlogloss:0.55306	eval-mlogloss:0.54545
[29]	train-mlogloss:0.54059	eval-mlogloss:0.53131
[30]	train-mlogloss:0.52946	eval-mlogloss:0.51941
[31]	train-mlogloss:0.52573	eval-mlogloss:0.51687

[I 2026-06-30 13:48:15,101] Trial 33 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:1.03759	eval-mlogloss:1.04722
[1]	train-mlogloss:0.90324	eval-mlogloss:0.90628

[I 2026-06-30 13:48:15,167] Trial 34 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08918	eval-mlogloss:1.08995
[1]	train-mlogloss:1.07449	eval-mlogloss:1.07457
[2]	train-mlogloss:1.06005	eval-mlogloss:1.05945
[3]	train-mlogloss:1.04526	eval-mlogloss:1.04432
[4]	train-mlogloss:1.03140	eval-mlogloss:1.02989
[5]	train-mlogloss:1.01723	eval-mlogloss:1.01462
[6]	train-mlogloss:1.00375	eval-mlogloss:1.00071
[7]	train-mlogloss:0.99085	eval-mlogloss:0.98705
[8]	train-mlogloss:0.97803	eval-mlogloss:0.97350
[9]	train-mlogloss:0.96532	eval-mlogloss:0.96020
[10]	train-mlogloss:0.95296	eval-mlogloss:0.94753
[11]	train-mlogloss:0.94099	eval-mlogloss:0.93474
[12]	train-mlogloss:0.93339	eval-mlogloss:0.92643
[13]	train-mlogloss:0.92151	eval-mlogloss:0.91343
[14]	train-mlogloss:0.91437	eval-mlogloss:0.90620
[15]	train-mlogloss:0.90388	eval-mlogloss:0.89505
[16]	train-mlogloss:0.89369	eval-mlogloss:0.88417
[17]	train-mlogloss:0.88482	eval-mlogloss:0.87469
[18]	train-mlogloss:0.87495	eval-mlogloss:0.86490
[19]	train-mlogloss:0.86600	eval-mlogloss:0.85565
[20]	train-mlogloss:0.85536	eval-mlogloss:0.84445
[21]	train-mlogloss:0.84473	eval-mlogloss:0.83264
[22]	train-mlogloss:0.83612	eval-mlogloss:0.82366
[23]	train-mlogloss:0.82587	eval-mlogloss:0.81275
[24]	train-mlogloss:0.81586	eval-mlogloss:0.80210
[25]	train-mlogloss:0.80604	eval-mlogloss:0.79145
[26]	train-mlogloss:0.79849	eval-mlogloss:0.78330
[27]	train-mlogloss:0.78913	eval-mlogloss:0.77364
[28]	train-mlogloss:0.78134	eval-mlogloss:0.76534
[29]	train-mlogloss:0.77189	eval-mlogloss:0.75507
[30]	train-mlogloss:0.76303	eval-mlogloss:0.74557
[31]	train-mlogloss:0.75611	eval-mlogloss:0.73863
[32]	train-mlogloss:0.74748	eval-mlogloss:0.72931
[33]	train-mlogloss:0.74219	eval-mlogloss:0.72343
[34]	train-mlogloss:0.73359	eval-mlogloss:0.71441
[35]	train-mlogloss:0.72533	eval-mlogloss:0.70552
[36]	train-mlogloss:0.71867	eval-mlogloss:0.69898
[37]	train-mlogloss:0.71052	eval-mlogloss:0.69046
[38]	train-mlogloss:0.70361	eval-mlogloss:0.68302
[39]	train-mlogloss:0.69640	eval-mlogloss:0.67540
[40]	train-mlogloss:0.69047	eval-mlogloss:0.66931
[41]	train-mlogloss:0.68276	eval-mlogloss:0.66086
[42]	train-mlogloss:0.67809	eval-mlogloss:0.65574
[43]	train-mlogloss:0.67173	eval-mlogloss:0.64903
[44]	train-mlogloss:0.66410	eval-mlogloss:0.64084
[45]	train-mlogloss:0.65820	eval-mlogloss:0.63492
[46]	train-mlogloss:0.65101	eval-mlogloss:0.62696
[47]	train-mlogloss:0.64385	eval-mlogloss:0.61942
[48]	train-mlogloss:0.63673	eval-mlogloss:0.61198
[49]	train-mlogloss:0.62988	eval-mlogloss:0.60471
[50]	train-mlogloss:0.62293	eval-mlogloss:0.59720
[51]	train-mlogloss:0.61684	eval-mlogloss:0.59072
[52]	train-mlogloss:0.61108	eval-mlogloss:0.58429
[53]	train-mlogloss:0.60457	eval-mlogloss:0.57703
[54]	train-mlogloss:0.59916	eval-mlogloss:0.57129
[55]	train-mlogloss:0.59278	eval-mlogloss:0.56445
[56]	train-mlogloss:0.58718	eval-mlogloss:0.55854
[57]	train-mlogloss:0.58112	eval-mlogloss:0.55181
[58]	train-mlogloss:0.57581	eval-mlogloss:0.54593
[59]	train-mlogloss:0.57062	eval-mlogloss:0.54060
[60]	train-mlogloss:0.56555	eval-mlogloss:0.53508
[61]	train-mlogloss:0.56171	eval-mlogloss:0.53137
[62]	train-mlogloss:0.55594	eval-mlogloss:0.52523
[63]	train-mlogloss:0.55169	eval-mlogloss:0.52040
[64]	train-mlogloss:0.54820	eval-mlogloss:0.51644
[65]	train-mlogloss:0.54248	eval-mlogloss:0.51033
[66]	train-mlogloss:0.53750	eval-mlogloss:0.50514
[67]	train-mlogloss:0.53203	eval-mlogloss:0.49936
[68]	train-mlogloss:0.52835	eval-mlogloss:0.49529
[69]	train-mlogloss:0.52321	eval-mlogloss:0.48982
[70]	train-mlogloss:0.51951	eval-mlogloss:0.48577
[71]	train-mlogloss:0.51463	eval-mlogloss:0.48057
[72]	train-mlogloss:0.50990	eval-mlogloss:0.47545
[73]	train-mlogloss:0.50490	eval-mlogloss:0.46997
[74]	train-mlogloss:0.50033	eval-mlogloss:0.46475
[75]	train-mlogloss:0.49691	eval-mlogloss:0.46136
[76]	train-mlogloss:0.49216	eval-mlogloss:0.45623
[77]	train-mlogloss:0.48844	eval-mlogloss:0.45237
[78]	train-mlogloss:0.48467	eval-mlogloss:0.44803
[79]	train-mlogloss:0.48002	eval-mlogloss:0.44292
[80]	train-mlogloss:0.47620	eval-mlogloss:0.43865
[81]	train-mlogloss:0.47234	eval-mlogloss:0.43480
[82]	train-mlogloss:0.46879	eval-mlogloss:0.43098
[83]	train-mlogloss:0.46610	eval-mlogloss:0.42804
[84]	train-mlogloss:0.46196	eval-mlogloss:0.42344
[85]	train-mlogloss:0.45845	eval-mlogloss:0.41957
[86]	train-mlogloss:0.45499	eval-mlogloss:0.41582
[87]	train-mlogloss:0.45155	eval-mlogloss:0.41191
[88]	train-mlogloss:0.44728	eval-mlogloss:0.40732
[89]	train-mlogloss:0.44312	eval-mlogloss:0.40274
[90]	train-mlogloss:0.43956	eval-mlogloss:0.39872
[91]	train-mlogloss:0.43638	eval-mlogloss:0.39550
[92]	train-mlogloss:0.43239	eval-mlogloss:0.39127
[93]	train-mlogloss:0.43008	eval-mlogloss:0.38895
[94]	train-mlogloss:0.42712	eval-mlogloss:0.38581
[95]	train-mlogloss:0.42351	eval-mlogloss:0.38157
[96]	train-mlogloss:0.42021	eval-mlogloss:0.37774
[97]	train-mlogloss:0.41686	eval-mlogloss:0.37388
[98]	train-mlogloss:0.41301	eval-mlogloss:0.36970
[99]	train-mlogloss:0.41029	eval-mlogloss:0.36662
[100]	train-mlogloss:0.40707	eval-mlogloss:0.36287
[101]	train-mlogloss:0.40367	eval-mlogloss:0.35914
[102]	train-mlogloss:0.40098	eval-mlogloss:0.35614
[103]	train-mlogloss:0.39769	eval-mlogloss:0.35268
[104]	train-mlogloss:0.39427	eval-mlogloss:0.34895
[105]	train-mlogloss:0.39176	eval-mlogloss:0.34619
[106]	train-mlogloss:0.38907	eval-mlogloss:0.34326
[107]	train-mlogloss:0.38651	eval-mlogloss:0.34041
[108]	train-mlogloss:0.38405	eval-mlogloss:0.33791
[109]	train-mlogloss:0.38113	eval-mlogloss:0.33455
[110]	train-mlogloss:0.37834	eval-mlogloss:0.33154
[111]	train-mlogloss:0.37596	eval-mlogloss:0.32892
[112]	train-mlogloss:0.37339	eval-mlogloss:0.32623
[113]	train-mlogloss:0.37118	eval-mlogloss:0.32351
[114]	train-mlogloss:0.36909	eval-mlogloss:0.32097
[115]	train-mlogloss:0.36660	eval-mlogloss:0.31830
[116]	train-mlogloss:0.36397	eval-mlogloss:0.31531
[117]	train-mlogloss:0.36094	eval-mlogloss:0.31192
[118]	train-mlogloss:0.35879	eval-mlogloss:0.30945
[119]	train-mlogloss:0.35703	eval-mlogloss:0.30746
[120]	train-mlogloss:0.35440	eval-mlogloss:0.30438
[121]	train-mlogloss:0.35161	eval-mlogloss:0.30117
[122]	train-mlogloss:0.34943	eval-mlogloss:0.29870
[123]	train-mlogloss:0.34744	eval-mlogloss:0.29646
[124]	train-mlogloss:0.34482	eval-mlogloss:0.29349
[125]	train-mlogloss:0.34255	eval-mlogloss:0.29068
[126]	train-mlogloss:0.34183	eval-mlogloss:0.29000
[127]	train-mlogloss:0.33983	eval-mlogloss:0.28784

[I 2026-06-30 13:48:15,530] Trial 35 pruned. Trial was pruned at iteration 128.

[0]	train-mlogloss:0.94539	eval-mlogloss:0.93383
[1]	train-mlogloss:0.82129	eval-mlogloss:0.79892

[I 2026-06-30 13:48:15,569] Trial 36 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.98523	eval-mlogloss:0.99011
[1]	train-mlogloss:0.87756	eval-mlogloss:0.87935

[I 2026-06-30 13:48:15,602] Trial 37 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.00770	eval-mlogloss:1.00385
[1]	train-mlogloss:0.94382	eval-mlogloss:0.93240
[2]	train-mlogloss:0.87085	eval-mlogloss:0.85661
[3]	train-mlogloss:0.80038	eval-mlogloss:0.78286
[4]	train-mlogloss:0.74225	eval-mlogloss:0.72181
[5]	train-mlogloss:0.68715	eval-mlogloss:0.66374
[6]	train-mlogloss:0.64059	eval-mlogloss:0.61623
[7]	train-mlogloss:0.60119	eval-mlogloss:0.57936

[I 2026-06-30 13:48:15,652] Trial 38 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.84507	eval-mlogloss:0.82721
[1]	train-mlogloss:0.66950	eval-mlogloss:0.64393

[I 2026-06-30 13:48:15,792] Trial 39 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.90291	eval-mlogloss:0.90821
[1]	train-mlogloss:0.68800	eval-mlogloss:0.68141

[I 2026-06-30 13:48:15,820] Trial 40 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.94617	eval-mlogloss:0.94266
[1]	train-mlogloss:0.82384	eval-mlogloss:0.79526

[I 2026-06-30 13:48:15,844] Trial 41 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.91174	eval-mlogloss:0.90209
[1]	train-mlogloss:0.80446	eval-mlogloss:0.77523

[I 2026-06-30 13:48:15,874] Trial 42 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.98228	eval-mlogloss:0.97182
[1]	train-mlogloss:0.82945	eval-mlogloss:0.80670

[I 2026-06-30 13:48:15,901] Trial 43 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.99886	eval-mlogloss:1.00899
[1]	train-mlogloss:0.80783	eval-mlogloss:0.79846

[I 2026-06-30 13:48:15,930] Trial 44 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.94371	eval-mlogloss:0.93227
[1]	train-mlogloss:0.82087	eval-mlogloss:0.80278

[I 2026-06-30 13:48:15,955] Trial 45 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.89083	eval-mlogloss:0.87871
[1]	train-mlogloss:0.73531	eval-mlogloss:0.71012

[I 2026-06-30 13:48:15,980] Trial 46 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.86855	eval-mlogloss:0.84964
[1]	train-mlogloss:0.70416	eval-mlogloss:0.67131

[I 2026-06-30 13:48:16,003] Trial 47 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.79746	eval-mlogloss:0.77722
[1]	train-mlogloss:0.66181	eval-mlogloss:0.61967

[I 2026-06-30 13:48:16,035] Trial 48 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03256	eval-mlogloss:1.03625
[1]	train-mlogloss:0.95657	eval-mlogloss:0.95915
[2]	train-mlogloss:0.88817	eval-mlogloss:0.88874
[3]	train-mlogloss:0.82717	eval-mlogloss:0.82625
[4]	train-mlogloss:0.77190	eval-mlogloss:0.76818
[5]	train-mlogloss:0.72048	eval-mlogloss:0.71425
[6]	train-mlogloss:0.67491	eval-mlogloss:0.66575
[7]	train-mlogloss:0.63318	eval-mlogloss:0.62191

[I 2026-06-30 13:48:16,079] Trial 49 pruned. Trial was pruned at iteration 8.

===============================
BEST HYPERPARAMETERS
===============================
lambda               : 5.983901338203304e-08
alpha                : 9.1113450684657e-06
eta                  : 0.1940290447101199
gamma                : 5.809704739686863e-05
max_depth            : 4
min_child_weight     : 6
subsample            : 0.5320212572787584
colsample_bytree     : 0.4497509937016343

===============================
BEST ACCURACY
===============================
1.0

In [42]:
from optuna.visualization import plot_intermediate_values

# 1. Plot intermediate values during the trials
plot_intermediate_values(study).show()