In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_csv("breast_cancer.csv")

In [3]:
df.head()

,Sample code number,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2

In [4]:
df.shape

(683, 11)

In [5]:
df.drop(columns=["Sample code number"] ,inplace=True)

In [6]:
df.head()

,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,5,1,1,1,2,1,3,1,1,2
1,5,4,4,5,7,10,3,2,1,2
2,3,1,1,1,2,2,3,1,1,2
3,6,8,8,1,3,4,3,7,1,2
4,4,1,1,3,2,1,3,1,1,2

In [7]:
df.shape

(683, 10)

In [8]:
X_train, X_test ,y_train ,y_test =train_test_split(df.iloc[ : , :-1] ,df.iloc[ : , -1],test_size=0.2)

In [9]:
X_train.head()

,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses
186,5,1,1,1,2,1,2,1,1
253,5,10,10,6,10,10,10,6,5
129,2,1,1,1,2,1,3,1,1
11,2,1,1,1,2,1,2,1,1
666,5,1,1,1,2,1,3,2,1

In [10]:
scaler= StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
X_train.shape

(546, 9)

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train.values)
y_test_tensor = torch.from_numpy(y_test.values)
y_train_tensor = (y_train_tensor == 4).float()
y_test_tensor = (y_test_tensor == 4).float()

In [13]:
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()
X_test_tensor = X_test_tensor.float()
y_test_tensor = y_test_tensor.float()

In [14]:
X_train_tensor.shape

torch.Size([546, 9])

In [15]:
X_train.dtype

dtype('float64')

In [16]:
y_train_tensor

tensor([0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1.,
        0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1.,
        0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0.,
        1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1.,
        1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0.,
        0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
        0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0.,
        0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0.,
        0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
        0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1.,
        0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1.,
        0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1.,
        1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0.,
        1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1.,
        0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0.,
        1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1.,
        0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
        0., 0., 0., 0., 0., 0.])

In [17]:
# #defining a model from scratch
# class NeuralNetwork():
#       def __init__(self , X):
#           self.weight = torch.rand(X.shape[1],1, dtype=torch.float64 , requires_grad=True)
#           self.bias = torch.zeros(1, dtype=torch.float64 , requires_grad =True)

#       def forward(self,X):
#           Z = torch.matmul(X,self.weight )+self.bias
#           y_pred = torch.sigmoid(Z)
#           return y_pred

#       def loss(self,y_pred,y):
#            # Clamp predictions to avoid log(0)
#             epsilon = 1e-7
#             y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        
#             # Calculate loss
#             loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
#             return loss

In [18]:
class NeuralNetwork(nn.Module):
    def __init__(self,num_feature):

        super().__init__()
        self.linear=nn.Linear(num_feature,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self, features):
        out=self.linear(features)
        out=self.sigmoid(out)

        return out
    # def loss(self,y_pred,y):
    #        # Clamp predictions to avoid log(0)
    #         epsilon = 1e-7
    #         y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        
    #         # Calculate loss
    #         loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    #         return loss

In [19]:
learning_rate=0.1
epochs=25

In [20]:
loss_funct=nn.BCELoss()

In [62]:
# print(X_train_tensor.dtype)
# print(model.linear.weight.dtype)

In [21]:
#training pipeline
#create model
model=NeuralNetwork(X_train_tensor.shape[1])

#define optimizer
optimizer=torch.optim.SGD(model.parameters() , lr=learning_rate)
y_train_tensor= y_train_tensor.unsqueeze(1)
#define loop
for epoch in range(epochs):
    #forward pass
    y_pred=model(X_train_tensor)
    
    #loss
    loss=loss_funct(y_pred , y_train_tensor)

    #zero gradient
    # model.linear.weight.grad.zero_()
    # model.linear.bias.grad.zero_()
    optimizer.zero_grad()
    
    #backward
    loss.backward()

    #parameter update
    # with torch.no_grad():
    #     model.linear.weight -= learning_rate * model.linear.weight.grad
    #     model.linear.bias -= learning_rate * model.linear.bias.grad
    optimizer.step()
   

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7450321316719055
Epoch: 2, Loss: 0.6360673308372498
Epoch: 3, Loss: 0.5541538596153259
Epoch: 4, Loss: 0.4914410412311554
Epoch: 5, Loss: 0.4422927796840668
Epoch: 6, Loss: 0.4028903841972351
Epoch: 7, Loss: 0.370662122964859
Epoch: 8, Loss: 0.34384652972221375
Epoch: 9, Loss: 0.32120710611343384
Epoch: 10, Loss: 0.30185407400131226
Epoch: 11, Loss: 0.28513169288635254
Epoch: 12, Loss: 0.2705465853214264
Epoch: 13, Loss: 0.25772058963775635
Epoch: 14, Loss: 0.24635909497737885
Epoch: 15, Loss: 0.2362292855978012
Epoch: 16, Loss: 0.22714467346668243
Epoch: 17, Loss: 0.21895433962345123
Epoch: 18, Loss: 0.21153473854064941
Epoch: 19, Loss: 0.2047838717699051
Epoch: 20, Loss: 0.19861678779125214
Epoch: 21, Loss: 0.1929621696472168
Epoch: 22, Loss: 0.18775981664657593
Epoch: 23, Loss: 0.18295837938785553
Epoch: 24, Loss: 0.1785140037536621
Epoch: 25, Loss: 0.17438890039920807

In [22]:
y_pred.shape

torch.Size([546, 1])

In [23]:
 y_train_tensor.shape

torch.Size([546, 1])

In [24]:
model.linear.weight

Parameter containing:
tensor([[0.3616, 0.2062, 0.2886, 0.5579, 0.3294, 0.6519, 0.0764, 0.4960, 0.0509]],
       requires_grad=True)

In [25]:
model.linear.bias

Parameter containing:
tensor([-0.0734], requires_grad=True)

In [26]:
#evaluation
with torch.no_grad():
    y_pred=model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')
print(y_pred)
print(y_test_tensor)

Accuracy: 0.5469657182693481
tensor([[0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.]])
tensor([0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1.,
        1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0.,
        0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1.,
        0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
        0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0.])