In [42]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [43]:
df=pd.read_csv("breast_cancer.csv")

In [44]:
df.head()

,Sample code number,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2

In [45]:
df.shape

(683, 11)

In [46]:
df.drop(columns=["Sample code number"] ,inplace=True)

In [47]:
df.head()

,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,5,1,1,1,2,1,3,1,1,2
1,5,4,4,5,7,10,3,2,1,2
2,3,1,1,1,2,2,3,1,1,2
3,6,8,8,1,3,4,3,7,1,2
4,4,1,1,3,2,1,3,1,1,2

In [48]:
df.shape

(683, 10)

In [49]:
X_train, X_test ,y_train ,y_test =train_test_split(df.iloc[ : , :-1] ,df.iloc[ : , -1],test_size=0.2)

In [50]:
X_train.head()

,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses
482,4,2,1,1,2,1,1,1,1
201,1,1,1,1,1,1,3,1,1
234,3,1,1,3,1,1,3,1,1
134,4,1,1,1,2,1,2,1,1
641,5,4,5,1,8,1,3,6,1

In [51]:
scaler= StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [52]:
X_train.shape

(546, 9)

In [53]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train.values)
y_test_tensor = torch.from_numpy(y_test.values)
y_train_tensor = (y_train_tensor == 4).float()
y_test_tensor = (y_test_tensor == 4).float()

In [54]:
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()
X_test_tensor = X_test_tensor.float()
y_test_tensor = y_test_tensor.float()

In [55]:
X_train_tensor.shape

torch.Size([546, 9])

In [56]:
X_train.dtype

dtype('float64')

In [57]:
y_train_tensor

tensor([0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1.,
        0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1.,
        1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
        1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1.,
        0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1.,
        1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0.,
        0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
        1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0.,
        0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
        1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1.,
        1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
        1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1.,
        0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0.,
        0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1.,
        0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1.,
        0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0.,
        1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0.,
        1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0.,
        1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
        0., 1., 1., 0., 0., 0.])

In [58]:
# #defining a model from scratch
# class NeuralNetwork():
#       def __init__(self , X):
#           self.weight = torch.rand(X.shape[1],1, dtype=torch.float64 , requires_grad=True)
#           self.bias = torch.zeros(1, dtype=torch.float64 , requires_grad =True)

#       def forward(self,X):
#           Z = torch.matmul(X,self.weight )+self.bias
#           y_pred = torch.sigmoid(Z)
#           return y_pred

#       def loss(self,y_pred,y):
#            # Clamp predictions to avoid log(0)
#             epsilon = 1e-7
#             y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        
#             # Calculate loss
#             loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
#             return loss

In [59]:
class NeuralNetwork(nn.Module):
    def __init__(self,num_feature):

        super().__init__()
        self.linear=nn.Linear(num_feature,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self, features):
        out=self.linear(features)
        out=self.sigmoid(out)

        return out
    # def loss(self,y_pred,y):
    #        # Clamp predictions to avoid log(0)
    #         epsilon = 1e-7
    #         y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        
    #         # Calculate loss
    #         loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    #         return loss

In [60]:
learning_rate=0.1
epochs=25

In [61]:
loss_funct=nn.BCELoss()

In [62]:
# print(X_train_tensor.dtype)
# print(model.linear.weight.dtype)

In [63]:
#training pipeline
#create model
model=NeuralNetwork(X_train_tensor.shape[1])
y_train_tensor= y_train_tensor.unsqueeze(1)
#define loop
for epoch in range(epochs):
    #forward pass
    y_pred=model(X_train_tensor)
    
    #loss
    loss=loss_funct(y_pred , y_train_tensor)

    #backward
    loss.backward()

    #parameter update
    with torch.no_grad():
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad

    #zero gradient
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.712287962436676
Epoch: 2, Loss: 0.6054956912994385
Epoch: 3, Loss: 0.525955855846405
Epoch: 4, Loss: 0.4656738042831421
Epoch: 5, Loss: 0.41889438033103943
Epoch: 6, Loss: 0.3817262649536133
Epoch: 7, Loss: 0.35156169533729553
Epoch: 8, Loss: 0.32662680745124817
Epoch: 9, Loss: 0.3056877851486206
Epoch: 10, Loss: 0.2878648638725281
Epoch: 11, Loss: 0.2725163698196411
Epoch: 12, Loss: 0.25916409492492676
Epoch: 13, Loss: 0.2474449872970581
Epoch: 14, Loss: 0.23707854747772217
Epoch: 15, Loss: 0.22784481942653656
Epoch: 16, Loss: 0.21956893801689148
Epoch: 17, Loss: 0.21211020648479462
Epoch: 18, Loss: 0.20535406470298767
Epoch: 19, Loss: 0.19920633733272552
Epoch: 20, Loss: 0.19358904659748077
Epoch: 21, Loss: 0.18843691051006317
Epoch: 22, Loss: 0.18369483947753906
Epoch: 23, Loss: 0.1793161928653717
Epoch: 24, Loss: 0.17526111006736755
Epoch: 25, Loss: 0.171495258808136

In [64]:
y_pred.shape

torch.Size([546, 1])

In [65]:
 y_train_tensor.shape

torch.Size([546, 1])

In [66]:
model.linear.weight

Parameter containing:
tensor([[0.4886, 0.3984, 0.4857, 0.5986, 0.5255, 0.2313, 0.0909, 0.0551, 0.1027]],
       requires_grad=True)

In [67]:
model.linear.bias

Parameter containing:
tensor([-0.2907], requires_grad=True)

In [68]:
#evaluation
with torch.no_grad():
    y_pred=model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')
print(y_pred)
print(y_test_tensor)

Accuracy: 0.5776546597480774
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.]])
tensor([0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0.,
        0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0.,
        1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0.,
        1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1.,
        0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.])